apiVersion: bootwright.io/v1alpha1
kind: StoragePlacementPolicy
metadata:
  name: stretch-datacenter

spec:
  clusterRef: ceph-multidc-01
  failureDomain: datacenter
  ruleName: stretch-rule

  replicated:
    size: 4
    minSize: 2
