apiVersion: bootwright.io/v1alpha1
kind: Host
metadata:
  name: services-host
spec:
  addresses:
    - name: ssh
      address: 192.168.10.11

  ssh:
    addressName: ssh
    keyRef:
      name: provider-host-ssh

  capabilities:
    - libvirt
    - container-runtime
