package datafoundation

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/crmarques/bootwright/api/v1alpha1"
	secret "github.com/crmarques/bootwright/internal/secrets"
	"github.com/crmarques/bootwright/internal/storage/topology"
)

const (
	GeneratedAtApplyPlaceholder = "BOOTWRIGHT_GENERATED_AT_APPLY_TIME"
	DefaultNamespace            = "openshift-storage"
	DefaultStorageClusterName   = "ocs-external-storagecluster"
)

type ExternalSecrets struct {
	AdminSecret          string `json:"adminSecret,omitempty"`
	FSID                 string `json:"fsid,omitempty"`
	MonSecret            string `json:"monSecret,omitempty"`
	HealthcheckerKey     string `json:"healthcheckerKey,omitempty"`
	RBDNodeKey           string `json:"rbdNodeKey,omitempty"`
	RBDProvisionerKey    string `json:"rbdProvisionerKey,omitempty"`
	CephFSNodeKey        string `json:"cephFSNodeKey,omitempty"`
	CephFSProvisionerKey string `json:"cephFSProvisionerKey,omitempty"`
	RGWAccessKey         string `json:"rgwAccessKey,omitempty"`
	RGWSecretKey         string `json:"rgwSecretKey,omitempty"`
}

type ExternalDetailsInput struct {
	ContainerCluster     string
	MonitorEndpoints     []string
	RBDPool              string
	CephFSName           string
	CephFSPool           string
	IncludeObjectGateway bool
	RGWEndpoint          string
	RGWPoolPrefix        string
}

func ExternalDetailsJSON(input ExternalDetailsInput, secrets ExternalSecrets) string {
	details, _ := json.MarshalIndent(externalDetails(input, secrets), "", "  ")
	return string(details)
}

func ExternalDetailsInputFromState(state v1alpha1.State, cluster v1alpha1.StorageCluster, export v1alpha1.StorageExport, containerCluster string) ExternalDetailsInput {
	df := export.Spec.DataFoundation
	input := ExternalDetailsInput{
		ContainerCluster: containerCluster,
		MonitorEndpoints: topology.MonitorEndpoints(state, cluster),
	}
	if df != nil {
		input.CephFSName = df.FilesystemRef.Name
		if fs, ok := topology.FilesystemByName(state, df.FilesystemRef.Name); ok {
			input.CephFSPool = topology.FilesystemDefaultDataPool(fs)
		}
		input.RBDPool = df.RBDPoolRef.Name
		input.RGWPoolPrefix = df.ObjectGatewayRef.Name
		if gw, ok := topology.GatewayByName(state, df.ObjectGatewayRef.Name); ok {
			// cephadm names RGW pools after the rgw service_id (no realm/zone is
			// rendered), so the Data Foundation poolPrefix must be the RGW
			// serviceID, not the StorageObjectGateway resource name.
			if gw.Spec.Ceph.ServiceID != "" {
				input.RGWPoolPrefix = gw.Spec.Ceph.ServiceID
			}
			if endpoint, endpointOK := topology.GatewayPublicEndpoint(gw); endpointOK {
				input.RGWEndpoint = fmt.Sprintf("%s:%d", endpoint.DNSName, topology.EndpointPort(endpoint, 443))
			}
		}
		input.IncludeObjectGateway = df.ObjectGatewayRef.Name != ""
	}
	return input
}

func ExternalDetailsSourceGenerated(export v1alpha1.StorageExport, cluster v1alpha1.StorageCluster) bool {
	if export.Spec.ExternalDetails == nil {
		return v1alpha1.StorageClusterManaged(cluster)
	}
	return export.Spec.ExternalDetails.Generated != nil
}

func ExternalDetailsSourceFromSecret(export v1alpha1.StorageExport) string {
	if export.Spec.ExternalDetails == nil {
		return ""
	}
	return strings.TrimSpace(export.Spec.ExternalDetails.FromSecretRef.Name)
}

func ExternalDetailsSourceSSH(export v1alpha1.StorageExport) *v1alpha1.StorageExportExternalDetailsSSHExecution {
	if export.Spec.ExternalDetails == nil {
		return nil
	}
	return export.Spec.ExternalDetails.SSHExecution
}

func LoadExternalDetailsSecretJSON(state v1alpha1.State, secretsDir string, name string) (string, error) {
	return LoadExternalDetailsSecretJSONForContext("test", state, secretsDir, name)
}

func LoadExternalDetailsSecretJSONForContext(contextName string, state v1alpha1.State, secretsDir string, name string) (string, error) {
	if strings.TrimSpace(name) == "" {
		return "", fmt.Errorf("data foundation externalDetails.fromSecretRef is required")
	}
	env := primaryEnvironment(state)
	path := secret.ResolvePath(name, env, secretsDir)
	resolver := secret.NewResolver(contextName, secretsDir, env)
	data, err := resolver.ReadMaterial(name, secret.MaterialPrimary)
	if err != nil {
		return "", fmt.Errorf("read data foundation external details secret %q at %s: %w", name, path, err)
	}
	return NormalizeExternalDetailsJSON(name, path, data)
}

func NormalizeExternalDetailsJSON(refName, path string, data []byte) (string, error) {
	details := strings.TrimSpace(string(data))
	if details == "" {
		return "", fmt.Errorf("data foundation external details secret %q at %s is empty", refName, path)
	}
	var entries []json.RawMessage
	if err := json.Unmarshal([]byte(details), &entries); err != nil {
		return "", fmt.Errorf("data foundation external details secret %q at %s must be the JSON array generated by ceph-external-cluster-details-exporter.py: %w", refName, path, err)
	}
	if entries == nil {
		return "", fmt.Errorf("data foundation external details secret %q at %s must be a JSON array", refName, path)
	}
	return details, nil
}

func ClientID(containerCluster, role string) string {
	return "bootwright." + containerCluster + "." + role
}

func RGWUserID(containerCluster string) string {
	return "bootwright." + containerCluster + ".rgw-admin"
}

func externalDetails(input ExternalDetailsInput, secrets ExternalSecrets) []map[string]any {
	details := []map[string]any{
		{
			"name": "rook-ceph-mon-endpoints",
			"kind": "ConfigMap",
			"data": map[string]any{
				"data":     strings.Join(input.MonitorEndpoints, ","),
				"maxMonId": fmt.Sprint(len(input.MonitorEndpoints) - 1),
				"mapping":  "{}",
			},
		},
		{"name": "rook-ceph-mon", "kind": "Secret", "data": map[string]any{"admin-secret": secretOrPlaceholder(secrets.AdminSecret), "fsid": secretOrPlaceholder(secrets.FSID), "mon-secret": secretOrPlaceholder(secrets.MonSecret)}},
		{"name": "rook-ceph-operator-creds", "kind": "Secret", "data": map[string]any{"userID": ClientID(input.ContainerCluster, "healthchecker"), "userKey": secretOrPlaceholder(secrets.HealthcheckerKey)}},
		{"name": "rook-csi-rbd-node", "kind": "Secret", "data": map[string]any{"userID": ClientID(input.ContainerCluster, "csi-rbd-node"), "userKey": secretOrPlaceholder(secrets.RBDNodeKey)}},
		{"name": "ceph-rbd", "kind": "StorageClass", "data": map[string]any{"pool": input.RBDPool}},
		{"name": "rook-csi-rbd-provisioner", "kind": "Secret", "data": map[string]any{"userID": ClientID(input.ContainerCluster, "csi-rbd-provisioner"), "userKey": secretOrPlaceholder(secrets.RBDProvisionerKey)}},
		{"name": "rook-csi-cephfs-provisioner", "kind": "Secret", "data": map[string]any{"adminID": ClientID(input.ContainerCluster, "csi-cephfs-provisioner"), "adminKey": secretOrPlaceholder(secrets.CephFSProvisionerKey)}},
		{"name": "rook-csi-cephfs-node", "kind": "Secret", "data": map[string]any{"adminID": ClientID(input.ContainerCluster, "csi-cephfs-node"), "adminKey": secretOrPlaceholder(secrets.CephFSNodeKey)}},
		{"name": "cephfs", "kind": "StorageClass", "data": map[string]any{"fsName": input.CephFSName, "pool": input.CephFSPool}},
	}
	if input.IncludeObjectGateway {
		details = append(details,
			map[string]any{"name": "ceph-rgw", "kind": "StorageClass", "data": map[string]any{"endpoint": input.RGWEndpoint, "poolPrefix": input.RGWPoolPrefix}},
			map[string]any{"name": "rgw-admin-ops-user", "kind": "Secret", "data": map[string]any{"userID": RGWUserID(input.ContainerCluster), "accessKey": secretOrPlaceholder(secrets.RGWAccessKey), "secretKey": secretOrPlaceholder(secrets.RGWSecretKey)}},
		)
	}
	return details
}

func secretOrPlaceholder(value string) string {
	if strings.TrimSpace(value) != "" {
		return value
	}
	return GeneratedAtApplyPlaceholder
}

func primaryEnvironment(state v1alpha1.State) *v1alpha1.Environment {
	if len(state.Environments) == 0 {
		return nil
	}
	return &state.Environments[0]
}
