apiVersion: bootwright.io/v1alpha1
kind: StorageExport
metadata:
  name: imported-ceph-odf
spec:
  type: dataFoundation

  storageClusterRef: imported-ceph

  externalDetails:
    fromSecretRef: imported-ceph-odf-details
