apiVersion: bootwright.io/v1alpha1
kind: StorageClusterBinding
metadata:
  name: imported-ceph-odf
spec:
  storageExportRef:
    name: imported-ceph-odf

  containerClusterSelector:
    names:
      - metal-ocp

