apiVersion: bootwright.io/v1alpha1
kind: InfraProvider
metadata:
  name: baremetal-provider
spec:
  type: baremetal

  baremetal:
    boot:
      method: external

  networkAttachments:

  - name: dc1-net
    baremetal:
      vlan: 0

  - name: dc2-net
    baremetal:
      vlan: 0
