apiVersion: bootwright.io/v1alpha1
kind: InfraProvider
metadata:
  name: baremetal-provider
spec:
  machines:
    - name: dc1-master-0
      baremetal:
        bootMACAddress: 52:54:00:41:10:10
        interfaces:
          - name: primary
            macAddress: 52:54:00:41:10:10
        rootDeviceHints:
          deviceName: /dev/sda
        bmc:
          address: redfish-virtualmedia+https://bmc-dc1-master-0.bootwright.test/redfish/v1/Systems/1
          credentialsRef:
            name: bmc-credentials
          disableCertificateVerification: true
    - name: dc1-master-1
      baremetal:
        bootMACAddress: 52:54:00:41:10:11
        interfaces:
          - name: primary
            macAddress: 52:54:00:41:10:11
        rootDeviceHints:
          deviceName: /dev/sda
        bmc:
          address: redfish-virtualmedia+https://bmc-dc1-master-1.bootwright.test/redfish/v1/Systems/1
          credentialsRef:
            name: bmc-credentials
          disableCertificateVerification: true
    - name: dc1-master-2
      baremetal:
        bootMACAddress: 52:54:00:41:10:12
        interfaces:
          - name: primary
            macAddress: 52:54:00:41:10:12
        rootDeviceHints:
          deviceName: /dev/sda
        bmc:
          address: redfish-virtualmedia+https://bmc-dc1-master-2.bootwright.test/redfish/v1/Systems/1
          credentialsRef:
            name: bmc-credentials
          disableCertificateVerification: true
    - name: dc2-master-0
      baremetal:
        bootMACAddress: 52:54:00:42:10:10
        interfaces:
          - name: primary
            macAddress: 52:54:00:42:10:10
        rootDeviceHints:
          deviceName: /dev/sda
        bmc:
          address: redfish-virtualmedia+https://bmc-dc2-master-0.bootwright.test/redfish/v1/Systems/1
          credentialsRef:
            name: bmc-credentials
          disableCertificateVerification: true
    - name: dc2-master-1
      baremetal:
        bootMACAddress: 52:54:00:42:10:11
        interfaces:
          - name: primary
            macAddress: 52:54:00:42:10:11
        rootDeviceHints:
          deviceName: /dev/sda
        bmc:
          address: redfish-virtualmedia+https://bmc-dc2-master-1.bootwright.test/redfish/v1/Systems/1
          credentialsRef:
            name: bmc-credentials
          disableCertificateVerification: true
    - name: dc2-master-2
      baremetal:
        bootMACAddress: 52:54:00:42:10:12
        interfaces:
          - name: primary
            macAddress: 52:54:00:42:10:12
        rootDeviceHints:
          deviceName: /dev/sda
        bmc:
          address: redfish-virtualmedia+https://bmc-dc2-master-2.bootwright.test/redfish/v1/Systems/1
          credentialsRef:
            name: bmc-credentials
          disableCertificateVerification: true

