apiVersion: bootwright.io/v1alpha1
kind: StorageCluster
metadata:
  name: ceph-external
spec:
  type: ceph

  ceph:
    distribution: redhat
    release: "9.0"
    entitlementRef: rhcs
    cephadm:
      bootstrap:
        node: node-01
    topology:
      nodes:
        - name: node-01
          machineRef: ceph-0
          roles:
            - mon
