apiVersion: bootwright.io/v1alpha1
kind: StorageExport
metadata:
  name: odf-external-ceph
spec:
  type: data-foundation

  storageClusterRef:
    name: ceph-stretch

  dataFoundation:
    rbdPoolRef:
      name: odf-rbd
    cephFSRef:
      name: odf-cephfs
    objectGatewayRef:
      name: odf-rgw
