apiVersion: bootwright.io/v1alpha1
kind: StoragePool
metadata:
  name: odf-rbd
spec:
  storageClusterRef:
    name: ceph-stretch

  placementPolicyRef:
    name: stretch-replicated

  ceph:
    type: replicated
    role: rbd
    replicated:
      size: 4
      minSize: 2
---
apiVersion: bootwright.io/v1alpha1
kind: StoragePool
metadata:
  name: odf-cephfs-metadata
spec:
  storageClusterRef:
    name: ceph-stretch

  placementPolicyRef:
    name: stretch-replicated

  ceph:
    type: replicated
    role: cephfs-metadata
    replicated:
      size: 4
      minSize: 2
---
apiVersion: bootwright.io/v1alpha1
kind: StoragePool
metadata:
  name: odf-cephfs-data
spec:
  storageClusterRef:
    name: ceph-stretch

  placementPolicyRef:
    name: stretch-replicated

  ceph:
    type: replicated
    role: cephfs-data
    replicated:
      size: 4
      minSize: 2
---
apiVersion: bootwright.io/v1alpha1
kind: StoragePool
metadata:
  name: odf-rgw
spec:
  storageClusterRef:
    name: ceph-stretch

  placementPolicyRef:
    name: stretch-replicated

  ceph:
    type: replicated
    role: rgw
    replicated:
      size: 4
      minSize: 2
