---
bootwright_virtctl_install_dir: /usr/local/bin
bootwright_virtctl_tmp_parent: /tmp
bootwright_virtctl_kubeconfig: ""
bootwright_virtctl_mirror_base: ""
bootwright_virtctl_console_clidownload: virtctl-clidownloads-kubevirt-hyperconverged
bootwright_virtctl_packages:
  - tar
  - gzip
