---
- name: Resolve BMC emulator parameters
  ansible.builtin.set_fact:
    bootwright_bmc_provider_name: "{{ bootwright_component.providerName }}"
    bootwright_bmc_libvirt_uri: "{{ bootwright_component.bmcEmulated.libvirtURI }}"
    bootwright_bmc_bind: "{{ bootwright_component.bmcEmulated.bindAddress }}"
    bootwright_bmc_port: "{{ bootwright_component.bmcEmulated.port }}"
    bootwright_bmc_vmedia_port: "{{ bootwright_component.bmcEmulated.vMediaPort }}"
    bootwright_bmc_cred_ref: "{{ bootwright_component.bmcEmulated.credentialsRef }}"
    bootwright_sushy_tools_version: "{{ bootwright_component.bmcEmulated.sushyToolsVersion }}"
  changed_when: false

- name: Resolve BMC state paths
  ansible.builtin.set_fact:
    bootwright_bmc_root: "{{ bootwright_provider_state_dir }}/bmc/{{ bootwright_bmc_provider_name }}"
    bootwright_bmc_temp_root: "{{ bootwright_provider_state_dir }}/bmc/{{ bootwright_bmc_provider_name }}/tmp"
    bootwright_bmc_vmedia_root: "/var/lib/libvirt/images/bootwright/{{ bootwright_provider_state_dir | dirname | basename }}/bmc/{{ bootwright_bmc_provider_name }}/vmedia"
  changed_when: false
