apiVersion: bootwright.io/v1alpha1
kind: ClusterExtensionSet
metadata:
  name: storage-virtualization-platform
spec:
  extensions:
    - name: openshift-data-foundation-operator
    - name: openshift-virtualization
