apiVersion: bootwright.io/v1alpha1
kind: ClusterExtension
metadata:
  name: openshift-data-foundation-operator
spec:
  type: olm-operator

  olm:
    namespace:
      name: openshift-storage
      create: true
      labels:
        openshift.io/cluster-monitoring: "true"

    operatorGroup:
      name: openshift-storage-operatorgroup
      targetNamespaces:
        - openshift-storage

    subscription:
      name: odf-operator
      package: odf-operator
      channel: stable-4.21
      source: redhat-operators
      sourceNamespace: openshift-marketplace
      installPlanApproval: Automatic

  readiness:
    timeout: 45m
    checks:
      - type: csvSucceeded
        namespace: openshift-storage
        subscription: odf-operator
