apiVersion: bootwright.io/v1alpha1
kind: InfraComponent
metadata:
  name: artifact-server
spec:
  type: artifactServer

  artifactServer:
    endpoints:
    - name: cluster
      listener: https
      machineAddress: cluster-lan
    machineRef:
      name: bastion
