apiVersion: bootwright.io/v1alpha1
kind: InfraComponent
metadata:
  name: artifact-server
spec:
  artifactServer:
    hostRef:
      name: lab-host
    endpoints:
      - name: cluster
        listener: https
        hostAddress: cluster-lan

