---
bootwright_provider_host_libvirt_packages:
  - qemu-system-x86
  - qemu-utils
  - libvirt-daemon-system
  - libvirt-clients
  - virtinst
  - python3-libvirt
bootwright_provider_host_libvirt_libvirt_service: libvirtd
