apiVersion: bootwright.io/v1alpha1
kind: InfraComponent
metadata:
  name: artifact-server
spec:
  type: artifactServer

  artifactServer:
    machineRef: bastion
    endpoints:
      - name: bmc
        listenerRef: https
        addressRef: lan
