apiVersion: bootwright.io/v1alpha1
kind: Machine
metadata:
  name: bastion
spec:
  capabilities:
    - container-runtime

  os:
    provided: true

  addresses:
    - name: ssh
      address: bastion.bootwright.test
    - name: lab-lan
      address: 192.168.160.5

  access:
    ssh:
      keyRef: bastion-host-ssh
      addressRef: ssh
