apiVersion: bootwright.io/v1alpha1
kind: StorageExport
metadata:
  name: shared-ceph-data-foundation
spec:
  type: data-foundation

  storageClusterRef:
    name: shared-ceph

  dataFoundation:
    externalDetailsRef:
      name: shared-ceph-external-details
