apiVersion: bootwright.io/v1alpha1
kind: ClusterAddonBinding
metadata:
  name: dc2-metal-ocp-addons
spec:
  clusterRef:
    name: dc2-metal-ocp

  addons:
    - name: openshift-virtualization
    - name: openshift-data-foundation
    - name: child-network

  storage:
    - name: ceph
      exportRef:
        name: odf-external-ceph
