apiVersion: bootwright.io/v1alpha1
kind: ContainerCluster
metadata:
  name: sno-disconnected
spec:
  distribution:
    release:
      version: 4.21.15

  install:
    mode: disconnected
    nodeSSH:
      keyPairRef:
        name: sno-disconnected-cluster-admin-ssh-key
    endpoints:
      api:
        address: 192.168.132.30
        source:
          type: external
      ingress:
        address: 192.168.132.31
        source:
          type: external

  nodes:

  - hostname: master-0
    role: master
    machineRef:
      name: sno-disconnected-master-0
