apiVersion: bootwright.io/v1alpha1
kind: ContainerCluster
metadata:
  name: sno-disconnected
spec:
  distribution:
    release:
      version: 4.21.15

  install:
    endpointRefs:
      api:
        name: api
      apiInt:
        name: api-int
      ingress:
        name: apps
    mode: disconnected
    nodeSSH:
      keyPairRef:
        name: sno-disconnected-cluster-admin-ssh-key

  networking:
    clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
    serviceNetwork:
      - 172.30.0.0/16

  nodes:
    - hostname: master-0
      role: master
      infraNodeRef:
        clusterInfra: sno-disconnected
        name: master-0
