apiVersion: bootwright.io/v1alpha1
kind: InfraProvider
metadata:
  name: lab-libvirt-provider
spec:
  machineProfiles:
    - name: sno
      cpu: 8
      memoryMiB: 16384
      diskGiB: 120
      libvirt:
        hostRef:
          name: lab-host
        uri: qemu:///system
        bmcEmulationDefaults:
          enabled: true
          auth:
            credentialRef:
              name: bmc-credentials

  networkAttachments:
    - name: sno-bridge
      libvirt:
        bridge: vbr-cb-sno-disc
