apiVersion: bootwright.io/v1alpha1
kind: Secret
metadata:
  name: openshift-pull-secret
spec:
  type: dockerConfigJson
---
apiVersion: bootwright.io/v1alpha1
kind: Secret
metadata:
  name: sno-disconnected-cluster-admin-ssh-key
spec:
  type: sshKeyPair

  source:
    generated:
      comment: bootwright-sno-disconnected-cluster-admin
---
apiVersion: bootwright.io/v1alpha1
kind: Secret
metadata:
  name: bastion-host-ssh
spec:
  type: sshKeyPair

  source:
    file:
      privateKey: ~/.ssh/bootwright-ssh-key
---
apiVersion: bootwright.io/v1alpha1
kind: Secret
metadata:
  name: bmc-credentials
spec:
  type: usernamePassword

  source:
    generated:
      username: admin
---
apiVersion: bootwright.io/v1alpha1
kind: Secret
metadata:
  name: proxy-credentials
spec:
  type: usernamePassword

  source:
    generated:
      username: proxy
---
apiVersion: bootwright.io/v1alpha1
kind: Secret
metadata:
  name: mirror-registry-credentials
spec:
  type: usernamePassword

  source:
    generated:
      username: mirror
---
apiVersion: bootwright.io/v1alpha1
kind: Secret
metadata:
  name: mirror-registry-ca
spec:
  type: caBundle

  source:
    generated:
      commonName: mirror.bootwright.test
      dnsNames:
        - mirror.bootwright.test
