apiVersion: bootwright.io/v1alpha1
kind: StoragePool
metadata:
  name: odf-cephfs-data

spec:
  clusterRef: ceph-multidc-01
  placementPolicyRef: stretch-datacenter
  type: replicated
  role: cephfs-data
  application: cephfs
