apiVersion: bootwright.io/v1alpha1
kind: StoragePool
metadata:
  name: odf-hub-multidc-02-rbd

spec:
  clusterRef: ceph-multidc-01
  placementPolicyRef: stretch-datacenter
  type: replicated
  role: rbd
  application: rbd
