---
collections:
  - name: https://galaxy.ansible.com/download/community-general-12.6.0.tar.gz
    type: url
  - name: https://galaxy.ansible.com/download/community-libvirt-2.2.0.tar.gz
    type: url
  - name: https://galaxy.ansible.com/download/containers-podman-1.20.1.tar.gz
    type: url
  - name: https://galaxy.ansible.com/download/ansible-posix-2.1.0.tar.gz
    type: url
  - name: https://galaxy.ansible.com/download/ansible-utils-6.0.2.tar.gz
    type: url
  - name: https://galaxy.ansible.com/download/community-vmware-6.2.0.tar.gz
    type: url
  - name: https://galaxy.ansible.com/download/vmware-vmware-2.8.0.tar.gz
    type: url
