apiVersion: bootwright.io/v1alpha1
kind: Environment
metadata:
  name: baremetal-redfish-multidc-virtualized-odf-ceph
spec:
  domains:
    base: bootwright.test

  infraComponents:
    artifactServers:
      - name: default
        management: managed
        componentRef: artifact-server
