apiVersion: bootwright.io/v1alpha1
kind: Proxy
metadata:
  name: lab-proxy

spec:
  management: managed
  machineRef: bastion
  implementation: squid
  bindAddress: 192.0.2.1
  port: 3128

  endpoints:
    - name: ip
      addressRef: ip
