---
bootwright_artifacts_container_name: "bootwright-artifacts-{{ bootwright_component.providerName }}-{{ bootwright_component.name }}"

bootwright_artifacts_root: "{{ bootwright_managed_services_dir }}/{{ bootwright_component.name }}"
bootwright_artifacts_config_dir: "{{ bootwright_artifacts_root }}/config"
bootwright_artifacts_tls_dir: "{{ bootwright_artifacts_root }}/tls"
bootwright_artifacts_public_dir: "{{ bootwright_artifacts_root }}/public"
bootwright_artifacts_tls_cert_path: "{{ bootwright_artifacts_tls_dir }}/server.crt"
bootwright_artifacts_tls_key_path: "{{ bootwright_artifacts_tls_dir }}/server.key"
bootwright_artifacts_config_path: "{{ bootwright_artifacts_config_dir }}/nginx.conf"
