apiVersion: bootwright.io/v1alpha1
kind: ClusterAddonBinding
metadata:
  name: dc1-child-ocp-addons
spec:
  clusterRef:
    name: dc1-child-ocp

  addons:
    - name: openshift-data-foundation

  storage:
    - name: ceph
      exportRef:
        name: odf-external-ceph
