apiVersion: bootwright.io/v1alpha1
kind: ContainerCluster
metadata:
  name: dc1-child-ocp
spec:
  distribution:
    release:
      version: 4.21.15

  install:
    nodeSSH:
      keyPairRef:
        name: dc1-child-ocp-cluster-admin-ssh-key
    platform:
      type: none
    endpoints:
      api:
        address: 192.168.151.20
        source:
          type: external
      api-int:
        address: 192.168.151.20
        source:
          type: external
      ingress:
        address: 192.168.151.21
        source:
          type: external

  networking:
    networkType: OVNKubernetes
    clusterNetwork:
    - cidr: 10.136.0.0/14
      hostPrefix: 23
    serviceNetwork:
    - 172.32.0.0/16

  nodes:

  - hostname: master-0
    role: master
    machineRef:
      name: dc1-child-ocp-infra-master-0

  - hostname: master-1
    role: master
    machineRef:
      name: dc1-child-ocp-infra-master-1

  - hostname: master-2
    role: master
    machineRef:
      name: dc1-child-ocp-infra-master-2

  - hostname: worker-0
    role: worker
    machineRef:
      name: dc1-child-ocp-infra-worker-0

  - hostname: worker-1
    role: worker
    machineRef:
      name: dc1-child-ocp-infra-worker-1

  - hostname: worker-2
    role: worker
    machineRef:
      name: dc1-child-ocp-infra-worker-2
