apiVersion: bootwright.io/v1alpha1
kind: Machine
metadata:
  name: dc1-child-ocp-infra-worker-1
spec:
  capabilities:
    - openshift-node

  substrate:
    providerRef: kubevirt-provider-dc1
    profileRef: dc1-child-worker

  os:
    provided: false

  network:
    config:
      networkConfigRef: dc1-child-net
      interfaceAttachments:
        - interface: primary
          attachmentRef: dc1-child-net
        - interface: ceph-public
          attachmentRef: dc1-ceph-public
      interfaceAddresses:
        - interface: primary
          addressRef: ip
          prefixLength: 24
      overrides:
        interfaces:
          - name: ceph-public
            ipv4:
              address:
                - ip: 192.168.171.71
                  prefix-length: 24

  addresses:
    - name: ip
      address: 192.168.151.41
    - name: ceph-public
      address: 192.168.171.71
