apiVersion: bootwright.io/v1alpha1
kind: ClusterAddonBinding
metadata:
  name: dc2-child-ocp-addons
spec:
  clusterRef: dc2-child-ocp

  addonRefs:
    - openshift-data-foundation

  addonConfigs:
    - addonRef: openshift-data-foundation
      inputs:
        - name: external-storage
          value: odf-external-ceph
