apiVersion: bootwright.io/v1alpha1
kind: ClusterAddonBinding
metadata:
  name: dc2-child-ocp-addons
spec:
  clusterRef: dc2-child-ocp

  addons:
    - name: openshift-data-foundation
      inputs:
        - name: external-storage
          values:
            exportRef: odf-external-ceph
