apiVersion: bootwright.io/v1alpha1
kind: Machine
metadata:
  name: dc2-child-ocp-infra-master-0
spec:
  capabilities:
    - openshift-node

  substrate:
    providerRef: kubevirt-provider-dc2
    profileRef: dc2-child-master

  os:
    provided: false

  network:
    config:
      networkConfigRef: dc2-child-net
      interfaceAddresses:
        - interface: primary
          addressRef: ip
          prefixLength: 24

  addresses:
    - name: ip
      address: 192.168.152.30
---
apiVersion: bootwright.io/v1alpha1
kind: Machine
metadata:
  name: dc2-child-ocp-infra-master-1
spec:
  capabilities:
    - openshift-node

  substrate:
    providerRef: kubevirt-provider-dc2
    profileRef: dc2-child-master

  os:
    provided: false

  network:
    config:
      networkConfigRef: dc2-child-net
      interfaceAddresses:
        - interface: primary
          addressRef: ip
          prefixLength: 24

  addresses:
    - name: ip
      address: 192.168.152.31
---
apiVersion: bootwright.io/v1alpha1
kind: Machine
metadata:
  name: dc2-child-ocp-infra-master-2
spec:
  capabilities:
    - openshift-node

  substrate:
    providerRef: kubevirt-provider-dc2
    profileRef: dc2-child-master

  os:
    provided: false

  network:
    config:
      networkConfigRef: dc2-child-net
      interfaceAddresses:
        - interface: primary
          addressRef: ip
          prefixLength: 24

  addresses:
    - name: ip
      address: 192.168.152.32
---
apiVersion: bootwright.io/v1alpha1
kind: Machine
metadata:
  name: dc2-child-ocp-infra-worker-0
spec:
  capabilities:
    - openshift-node

  substrate:
    providerRef: kubevirt-provider-dc2
    profileRef: dc2-child-worker

  os:
    provided: false

  network:
    config:
      networkConfigRef: dc2-child-net
      interfaceAddresses:
        - interface: primary
          addressRef: ip
          prefixLength: 24

  addresses:
    - name: ip
      address: 192.168.152.40
---
apiVersion: bootwright.io/v1alpha1
kind: Machine
metadata:
  name: dc2-child-ocp-infra-worker-1
spec:
  capabilities:
    - openshift-node

  substrate:
    providerRef: kubevirt-provider-dc2
    profileRef: dc2-child-worker

  os:
    provided: false

  network:
    config:
      networkConfigRef: dc2-child-net
      interfaceAddresses:
        - interface: primary
          addressRef: ip
          prefixLength: 24

  addresses:
    - name: ip
      address: 192.168.152.41
---
apiVersion: bootwright.io/v1alpha1
kind: Machine
metadata:
  name: dc2-child-ocp-infra-worker-2
spec:
  capabilities:
    - openshift-node

  substrate:
    providerRef: kubevirt-provider-dc2
    profileRef: dc2-child-worker

  os:
    provided: false

  network:
    config:
      networkConfigRef: dc2-child-net
      interfaceAddresses:
        - interface: primary
          addressRef: ip
          prefixLength: 24

  addresses:
    - name: ip
      address: 192.168.152.42
