apiVersion: bootwright.io/v1alpha1
kind: ContainerCluster
metadata:
  name: dc2-child-ocp
spec:
  distribution:
    type: openshift # default
    release:
      version: 4.21.15

  install:
    method: agent # default
    mode: connected # default
    pullSecretRef:
      name: openshift-pull-secret # inherited from Environment.defaults.install
    nodeSSH:
      keyPairRef:
        name: cluster-admin-ssh-key # inherited from Environment.defaults.install

  controlPlane:
    name: master
    replicas: 3

  compute:
    - name: worker
      replicas: 3

  networking:
    networkType: OVNKubernetes
    clusterNetwork:
      - cidr: 10.140.0.0/14
        hostPrefix: 23
    serviceNetwork:
      - 172.33.0.0/16

  nodes:
    - hostname: master-0
      role: master
      machineRef:
        clusterInfra: dc2-child-ocp-infra
        name: master-0
    - hostname: master-1
      role: master
      machineRef:
        clusterInfra: dc2-child-ocp-infra
        name: master-1
    - hostname: master-2
      role: master
      machineRef:
        clusterInfra: dc2-child-ocp-infra
        name: master-2
    - hostname: worker-0
      role: worker
      machineRef:
        clusterInfra: dc2-child-ocp-infra
        name: worker-0
    - hostname: worker-1
      role: worker
      machineRef:
        clusterInfra: dc2-child-ocp-infra
        name: worker-1
    - hostname: worker-2
      role: worker
      machineRef:
        clusterInfra: dc2-child-ocp-infra
        name: worker-2
