apiVersion: bootwright.io/v1alpha1
kind: ClusterAddonBinding
metadata:
  name: metal-ocp-odf
spec:
  clusterRef: metal-ocp

  addonRefs:
    - openshift-data-foundation

  addonConfigs:
    - addonRef: openshift-data-foundation
      inputs:
        - name: external-storage
          value: imported-ceph-odf
