apiVersion: bootwright.io/v1alpha1
kind: Machine
metadata:
  name: metal-master-0
spec:
  capabilities:
  - openshift-node

  substrate:
    providerRef:
      name: baremetal-provider
    bareMetal:
      bootMACAddress: 52:54:00:60:10:10
      interfaces:
      - name: primary
        macAddress: 52:54:00:60:10:10
      rootDeviceHints:
        deviceName: /dev/sda
      bmc:
        address: redfish-virtualmedia+https://bmc-metal-master-0.bootwright.test/redfish/v1/Systems/1
        credentialsRef:
          name: bmc-credentials
        disableCertificateVerification: true

  os:
    mode: raw
    install:
      network:
        networkConfigRef:
          name: metal-net
        overrides:
          interfaces:
          - name: primary
            ipv4:
              address:
              - ip: 192.168.160.20
                prefix-length: 24
        attachmentRef:
          name: metal-net
