apiVersion: bootwright.io/v1alpha1
kind: StorageCluster
metadata:
  name: ceph-ibm
spec:
  type: ceph

  management: managed

  ceph:
    distribution: ibm

    release: "9.9.1"

    ibm:
      callHome: disabled

    entitlementRef: ibm-storage-ceph

    security:
      fips:
        enabled: true

    cephadm:
      addressRef: ssh
      bootstrap:
        host: node01

    networks:
      publicCIDRs:
        - 192.168.140.0/24
      clusterCIDRs:
        - 192.168.140.0/24

    management:
      dnsName: dashboard.ceph.bootwright.test
      ingress:
        name: lab
        address: 192.168.140.81
        prefixLength: 24
        virtualInterfaceNetworks:
          - 192.168.140.0/24
        placement:
          hosts:
            - node01
            - node02

    topology:
      hosts:
        - machineRef: ceph-1
          site: lab
          roles:
            - mon
            - mgr
            - osd
            - mds
            - rgw
            - ingress
          devices:
            - /dev/vdb
            - /dev/vdc
            - /dev/vdd
        - machineRef: ceph-2
          site: lab
          roles:
            - mon
            - mgr
            - osd
            - mds
            - rgw
            - ingress
          devices:
            - /dev/vdb
            - /dev/vdc
            - /dev/vdd
        - machineRef: ceph-3
          site: lab
          roles:
            - mon
