apiVersion: bootwright.io/v1alpha1
kind: Environment
metadata:
  name: baremetal-redfish-fleet
spec:
  baseDomain: bootwright.test

  defaults:
    artifactAccess:
      serverRef:
        name: default
      redfishVirtualMedia:
        endpointRef:
          name: bmc

  resources:
    - infra
    - clusters

  secrets:
    - openshift-pull-secret
    - dc1-ocp-cluster-admin-ssh-key:
        generated:
          sshKeyPair:
            comment: bootwright-dc1-ocp-cluster-admin
    - dc2-ocp-cluster-admin-ssh-key:
        generated:
          sshKeyPair:
            comment: bootwright-dc2-ocp-cluster-admin
    - bastion-host-ssh:
        file: ~/.ssh/bootwright-ssh-key
    - bmc-credentials

  infraComponents:
    artifactServers:
      - name: default
        type: managed
        componentRef:
          name: artifact-server
