apiVersion: bootwright.io/v1alpha1
kind: Environment
metadata:
  name: demo-fleet
spec:
  baseDomain: example.test

  resources:
    - hosts.yaml
    - networks.yaml
    - provider.yaml
    - infra-component.yaml
    - cluster-infra.yaml
    - container-cluster.yaml

  secrets:
    openshift-pull-secret: null
    cluster-admin-pub-key:
      generated:
        sshKeyPair:
          type: ed25519
          comment: bootwright-cluster-admin
    provider-host-ssh:
      file: ~/.ssh/bootwright-ssh-key
    bmc-credentials:
      generated:
        credentials:
          username: admin

  infraComponents:
    artifactServers:
      - name: default
        type: managed
        default: true
        componentRef:
          name: artifact-server
        routes:
          redfishVirtualMedia:
            endpoint: bmc
          clusterInstall:
            endpoint: cluster
