apiVersion: bootwright.io/v1alpha1
kind: Machine
metadata:
  name: storage-a-02

spec:
  capabilities:
    - ceph-node

  placement:
    site: site-a

  substrate:
    providerRef: bare-metal

  os:
    provided: false
    installProfileRef: rhel-ceph-node
    install:
      rootDeviceHints:
        deviceName: /dev/sda

  network:
    configRef: ceph-network
    attachmentRef: ceph-network
    installAddressRef: ssh

    addresses:
      - name: fqdn
        address: storage-a-02.example.com

      - name: ssh
        address: 198.51.100.2/25
        interface: bond0.200

      - name: cluster
        address: 203.0.113.2/24
        interface: bond0.300

    interfaceBinding:
      - nicRef: eth0
        interfaceName: eth0

      - nicRef: eth1
        interfaceName: eth1

      - nicRef: eth2
        interfaceName: eth2

      - nicRef: eth3
        interfaceName: eth3

    overrides: {}

  hardware:
    nics:
      - name: eth0
        macAddress: 02:00:00:00:00:04

      - name: eth1
        macAddress: 02:00:00:00:00:05

      - name: eth2
        macAddress: 02:00:00:00:00:06

      - name: eth3
        macAddress: 02:00:00:00:00:07

    boot:
      nicRef: eth0

    management:
      bmc:
        address: redfish-virtualmedia+https://bmc-storage-a-02.example.com/redfish/v1/Systems/1
        protocol: redfish
        credentialsRef: ceph-bmc-credentials
        tls:
          verify: true
        virtualMedia:
          tls:
            trust: established
