---
bootwright_machine_setup_libvirt_packages:
  - qemu-system-x86
  - qemu-utils
  - libvirt-daemon-system
  - libvirt-clients
  - virtinst
  - python3-libvirt
bootwright_machine_setup_libvirt_libvirt_service: libvirtd
