apiVersion: k8s.ovn.org/v1
kind: ClusterUserDefinedNetwork
metadata:
  name: dc1-child-net
spec:
  namespaceSelector:
    matchLabels:
      bootwright.io/cudn: dc1-child-net
  network:
    topology: Localnet
    localnet:
      role: Secondary
      ipam:
        mode: Disabled
      physicalNetworkName: dc1-child
      mtu: 1500
