apiVersion: k8s.ovn.org/v1
kind: ClusterUserDefinedNetwork
metadata:
  name: dc2-ceph-public
spec:
  namespaceSelector:
    matchLabels:
      bootwright.io/ceph-public-cudn: dc2-ceph-public
  network:
    topology: Localnet
    localnet:
      role: Secondary
      ipam:
        mode: Disabled
      physicalNetworkName: dc2-ceph-public
      mtu: 9000
