---
- import_playbook: check_external_reachability.yml

- name: Check host prerequisites
  hosts: bootwright_provider_hosts:bootwright_infra_component_hosts:bootwright_boot_hosts:bootwright_storage_hosts
  gather_subset:
    - "!all"
    - min
    - env
  become: false
  environment: "{{ bootwright_proxy_env | default({}) }}"

  pre_tasks:
    - name: Resolve proxy environment
      ansible.builtin.import_role:
        name: bootwright.core.machine_proxy
        tasks_from: facts

  tasks:
    - name: Check generic host prerequisites
      ansible.builtin.import_role:
        name: bootwright.core.check_host_preflight

    - name: Check storage host prerequisites
      ansible.builtin.import_role:
        name: bootwright.core.check_storage_preflight
