apiVersion: bootwright.io/v1alpha1
kind: ContainerCluster
metadata:
  name: sno

spec:
  distribution:
    type: openshift

    release:
      version: 4.21.33
      channel: stable-4.21

  install:
    method: agent
    mode: connected

    platform:
      type: none

    endpoints:
      api:
        source:
          type: node
      ingress:
        source:
          type: node

    agent:
      redfishVirtualMedia:
        artifactServerEndpoint:
          serverRef: lab-artifacts
          endpointRef: ip-https

    proxy:
      proxyRef: lab-proxy
      endpointRef: ip
      noProxy:
        - .lab.example.test
        - 192.0.2.0/24

    ntp:
      - serverRef: lab-ntp
        endpointRef: ip

    pullSecretRef: openshift-pull-secret

    nodeSSH:
      keyPairRef: sno-cluster-admin-ssh-key

  nodes:
    - name: master-01
      role: master
      machineRef: sno-master-01
