apiVersion: bootwright.io/v1alpha1
kind: StorageExport
metadata:
  name: ceph-multidc-01-odf-hub-multidc-01
spec:
  storageClusterRef: ceph-multidc-01

  dataFoundation:
    rbdPoolRef: odf-hub-multidc-01-rbd
    filesystemRef: odf-cephfs
    objectGatewayRef: odf-rgw-all
