apiVersion: bootwright.io/v1alpha1
kind: Environment
metadata:
  name: imported-ceph-data-foundation
spec:
  baseDomain: example.test

  resources:
    - shared/hosts.yaml
    - shared/networks.yaml
    - shared/provider.yaml
    - shared/infra-component.yaml
    - clusters/dc1-ocp/cluster-infra.yaml
    - clusters/dc1-ocp/container-cluster.yaml
    - clusters/dc2-ocp/cluster-infra.yaml
    - clusters/dc2-ocp/container-cluster.yaml
    - storage/storage-cluster.yaml
    - storage/storage-export.yaml
    - storage/storage-cluster-binding.yaml
    - extensions/cluster-extension-openshift-data-foundation-operator.yaml
    - extensions/cluster-extension-binding.yaml

  secrets:
    openshift-pull-secret: null
    cluster-admin-ssh-key:
      generated:
        sshKeyPair:
          type: ed25519
          comment: bootwright-cluster-admin
    provider-host-ssh:
      file: ~/.ssh/bootwright-ssh-key
    bmc-credentials:
      generated:
        credentials:
          username: admin
    shared-ceph-external-details:
      file: ../secrets/shared-ceph-external-cluster-details.json

  infraComponents:
    artifactServers:
      - name: default
        type: managed
        default: true
        componentRef:
          name: artifact-server
        routes:
          redfishVirtualMedia:
            endpoint: bmc
          clusterInstall:
            endpoint: cluster
