apiVersion: bootwright.io/v1alpha1
kind: Environment
metadata:
  name: baremetal-redfish-imported-ceph-odf
spec:
  domains:
    base: bootwright.test

  infraComponents:
    artifactServers:
      - name: default
        management: managed
        componentRef: artifact-server
