package ceph

import (
	"fmt"
	"strings"

	"github.com/crmarques/bootwright/api/v1alpha1"
	"github.com/crmarques/bootwright/internal/host/shellquote"
	"github.com/crmarques/bootwright/internal/storage/topology"
)

type CephScriptOptions struct {
	LibFile              string
	BootstrapConfFile    string
	BootstrapSpecFile    string
	CoreServicesSpecFile string
	LateServicesSpecFile string
}

func CephApplyScript(state v1alpha1.State, cluster v1alpha1.StorageCluster, opts CephScriptOptions) string {
	var b strings.Builder
	name := cluster.Metadata.Name

	b.WriteString("#!/usr/bin/env bash\n")
	fmt.Fprintf(&b, "# Generated by bootwright render for storage cluster %q. Do not edit.\n", name)
	b.WriteString("# Reproduces the Ceph objects bootwright configures from its input files\n")
	b.WriteString("# using native CLIs (cephadm / ceph / radosgw-admin / rbd) instead of\n")
	b.WriteString("# 'bootwright apply'. Re-runnable: create-style steps are guarded and\n")
	b.WriteString("# skip-if-exists; set-* steps reconcile in place. The data-destroying\n")
	b.WriteString("# --override rebuild path is bootwright-only and is not generated here.\n")
	b.WriteString("set -euo pipefail\n")
	b.WriteString(`HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"` + "\n")
	b.WriteString("# shellcheck source=/dev/null\n")
	fmt.Fprintf(&b, "source \"$HERE/%s\"\n\n", opts.LibFile)

	writeBootstrapStage(&b, state, cluster, opts)

	b.WriteString("\necho \"== stage 10: host and core service specs (ceph orch apply) ==\"\n")
	writeOrchApply(&b, opts.BootstrapSpecFile)
	writeOrchApply(&b, opts.CoreServicesSpecFile)

	b.WriteString("\necho \"== stage 20: ceph objects ==\"\n")
	var lateOps []map[string]any
	for _, op := range cephOperationList(state, cluster) {
		if op["phase"] == "object-gateway" {
			lateOps = append(lateOps, op)
			continue
		}
		writeOperation(&b, op)
	}

	b.WriteString("\necho \"== stage 30: late service specs (ceph orch apply) ==\"\n")
	writeOrchApply(&b, opts.LateServicesSpecFile)

	if len(lateOps) > 0 {
		b.WriteString("\necho \"== stage 40: object-gateway objects (after the rgw/nfs services above) ==\"\n")
		for _, op := range lateOps {
			writeOperation(&b, op)
		}
	}

	if ManagementHasSecrets(cluster) {
		b.WriteString("\necho \"  [todo] spec.ceph.management carries TLS/oauth2-proxy secrets: the mgmt-gateway is NOT in this bundle.\"\n")
		b.WriteString("echo \"  [todo] The keepalive ingress above fronts it, so its VIP has no backend until you apply the\"\n")
		b.WriteString("echo \"  [todo] mgmt-gateway spec with your cert/secret files (or run 'bootwright apply --clusters <cluster>').\"\n")
	}

	fmt.Fprintf(&b, "\necho \"bootwright: ceph apply complete for %s\"\n", name)
	return b.String()
}

func cephOperationList(state v1alpha1.State, cluster v1alpha1.StorageCluster) []map[string]any {
	ops, _ := CephOperations(state, cluster)["operations"].([]map[string]any)
	return ops
}

func writeOrchApply(b *strings.Builder, file string) {
	if file == "" {
		return
	}
	fmt.Fprintf(b, "bw_run ceph orch apply -i \"$HERE/%s\"\n", file)
}

func writeBootstrapStage(b *strings.Builder, state v1alpha1.State, cluster v1alpha1.StorageCluster, opts CephScriptOptions) {
	ceph := cluster.Spec.Ceph
	args := []string{
		"cephadm", "bootstrap",
		"--mon-ip", topology.NodeAddressByRef(state, cluster, ceph.Cephadm.Bootstrap.Host, ceph.Cephadm.Bootstrap.AddressRef.Name),
		"--allow-fqdn-hostname",
		"--dashboard-password-noupdate",
	}
	if ceph.Cephadm.Bootstrap.SingleHostDefaults {
		args = append(args, "--single-host-defaults")
	}
	if cidrs := ceph.Networks.ClusterCIDRs; len(cidrs) > 0 {
		args = append(args, "--cluster-network", strings.Join(cidrs, ","))
	}
	if !MonitoringEnabled(cluster) {
		args = append(args, "--skip-monitoring-stack")
	}

	b.WriteString("echo \"== stage 00: cephadm bootstrap ==\"\n")
	b.WriteString("if [[ -f /etc/ceph/ceph.conf ]]; then\n")
	b.WriteString("  echo \"  [skip] cephadm bootstrap: /etc/ceph/ceph.conf present\"\n")
	b.WriteString("else\n")
	fmt.Fprintf(b, "  bootstrap=(%s", shellquote.Quote(args))
	if opts.BootstrapConfFile != "" {
		fmt.Fprintf(b, " --config \"$HERE/%s\"", opts.BootstrapConfFile)
	}
	b.WriteString(")\n")
	b.WriteString("  # Extra bootstrap flags from the environment, e.g. --registry-json <file>\n")
	b.WriteString("  # for authenticated (Red Hat / IBM) registries, or --image <ref>.\n")
	b.WriteString("  # shellcheck disable=SC2206\n")
	b.WriteString("  [[ -n \"${BW_CEPHADM_BOOTSTRAP_EXTRA:-}\" ]] && bootstrap+=(${BW_CEPHADM_BOOTSTRAP_EXTRA})\n")
	b.WriteString("  bw_run \"${bootstrap[@]}\"\n")
	b.WriteString("fi\n")
}

func writeOperation(b *strings.Builder, op map[string]any) {
	name := opString(op, "name")
	cmd := opCommand(op)
	kind, resName, guarded := opIdempotency(op)
	fmt.Fprintf(b, "# %s\n", name)
	if len(cmd) == 0 {
		if kind == "stretch-crush-rule" {
			domain, replicas := stretchRuleParams(op)
			fmt.Fprintf(b, "bw_stretch_crush_rule %s\n", shellquote.QuoteWords([]string{resName, domain, replicas}))
			return
		}
		fmt.Fprintf(b, "echo \"  [todo] %s cannot be expressed as a native command; apply it with 'bootwright apply --clusters <cluster>'\"\n", name)
		return
	}
	sensitive := opSensitive(op)
	switch {
	case guarded && sensitive:
		fmt.Fprintf(b, "bw_guarded_quiet %s\n", shellquote.QuoteWords(append([]string{kind, resName, name}, cmd...)))
	case guarded:
		fmt.Fprintf(b, "bw_guarded %s\n", shellquote.QuoteWords(append([]string{kind, resName}, cmd...)))
	case sensitive:
		fmt.Fprintf(b, "bw_run_quiet %s\n", shellquote.QuoteWords(append([]string{name}, cmd...)))
	default:
		fmt.Fprintf(b, "bw_run %s\n", shellquote.QuoteWords(cmd))
	}
}

func stretchRuleParams(op map[string]any) (domain, replicas string) {
	replicas = "2"
	if s, ok := op["structural"].(map[string]any); ok {
		domain, _ = s["failureDomain"].(string)
		if r, ok := s["replicasPerFailureDomain"]; ok {
			replicas = fmt.Sprint(r)
		}
	}
	return domain, replicas
}

func opString(op map[string]any, key string) string {
	if v, ok := op[key].(string); ok {
		return v
	}
	return ""
}

func opCommand(op map[string]any) []string {
	if cmd, ok := op["command"].([]string); ok {
		return cmd
	}
	return nil
}

func opIdempotency(op map[string]any) (kind, name string, ok bool) {
	m, has := op["idempotency"].(map[string]any)
	if !has {
		return "", "", false
	}
	kind, _ = m["kind"].(string)
	name, _ = m["name"].(string)
	return kind, name, kind != ""
}

func opSensitive(op map[string]any) bool {
	if nolog, ok := op["no_log"].(bool); ok && nolog {
		return true
	}
	_, hasCapture := op["capture"]
	return hasCapture
}

func CephApplyLib() string {
	return cephApplyLib
}

const cephApplyLib = `#!/usr/bin/env bash
# Generated by bootwright render. Do not edit.
#
# Shared helpers for the per-cluster Ceph apply script (apply.sh). Each guard
# mirrors the idempotency probe bootwright's apply role uses, so re-running
# apply.sh converges instead of erroring on already-created objects.
#
# Execution model: commands run where the Ceph admin keyring is available --
# normally ON the cephadm bootstrap host after 'cephadm bootstrap'. To target a
# remote or containerized CLI, export BW_CEPH_PREFIX, e.g.
#   export BW_CEPH_PREFIX="cephadm shell --"
#   export BW_CEPH_PREFIX="ssh root@mon-a --"
# It is word-split and prepended to every native invocation.

set -euo pipefail

if ! command -v jq >/dev/null 2>&1; then
  echo "bootwright: 'jq' is required by the idempotency guards but is not on PATH" >&2
  exit 1
fi

# shellcheck disable=SC2206
_bw_prefix=(${BW_CEPH_PREFIX:-})

# _bw_exec <argv...>: run a native command through the optional exec prefix.
_bw_exec() { "${_bw_prefix[@]}" "$@"; }

# bw_run <argv...>: run an in-place reconcile (idempotent) command.
bw_run() {
  echo "  [run ] $*"
  _bw_exec "$@"
}

# bw_run_quiet <label> <argv...>: run a command whose OUTPUT is sensitive (auth
# keys); the command line label is shown but stdout is discarded.
bw_run_quiet() {
  local label="$1"; shift
  echo "  [run ] ${label} (output redacted)"
  _bw_exec "$@" >/dev/null
}

# bw_guarded <kind> <name> <argv...>: run a create-style command unless the
# resource already exists (existence probe keyed by <kind>).
bw_guarded() {
  local kind="$1" name="$2"; shift 2
  if _bw_exists "$kind" "$name"; then
    echo "  [skip] ${kind} '${name}' already present"
    return 0
  fi
  echo "  [run ] $*"
  _bw_exec "$@"
}

# bw_guarded_quiet <kind> <name> <label> <argv...>: guarded, sensitive output
# discarded.
bw_guarded_quiet() {
  local kind="$1" name="$2" label="$3"; shift 3
  if _bw_exists "$kind" "$name"; then
    echo "  [skip] ${kind} '${name}' already present"
    return 0
  fi
  echo "  [run ] ${label} (output redacted)"
  _bw_exec "$@" >/dev/null
}

_bw_has_string() { jq -e --arg n "$2" 'any(.[]; . == $n)' >/dev/null 2>&1 <<<"$1"; }
_bw_has_attr() { jq -e --arg a "$2" --arg n "$3" 'any(.[]; .[$a] == $n)' >/dev/null 2>&1 <<<"$1"; }

# bw_stretch_crush_rule <rule> <failure-domain> <replicas-per-domain>: create the
# stretch CRUSH rule (two replicas per failure domain) that the enable-stretch and
# pool-crush-rule steps depend on. 'ceph osd crush rule create-replicated' cannot
# express the two-step rule, so it is compiled into the CRUSH map. crushtool is
# not on the host, so the de/compile steps run inside 'cephadm shell'. No-op if
# the rule already exists. Must run as root on the bootstrap host.
bw_stretch_crush_rule() {
  local rule="$1" domain="$2" replicas="$3"
  if _bw_has_attr "$(_bw_exec ceph osd crush rule dump --format json)" rule_name "$rule"; then
    echo "  [skip] crush-rule '${rule}' already present"
    return 0
  fi
  echo "  [run ] compile stretch CRUSH rule '${rule}'"
  local work rid
  work="$(mktemp -d)"
  rid="$(_bw_exec ceph osd crush rule dump --format json | jq '([.[].rule_id] + [0]) | max + 1')"
  _bw_exec ceph osd getcrushmap -o "${work}/crushmap.bin"
  _bw_exec cephadm shell --mount "${work}:/mnt" -- crushtool -d /mnt/crushmap.bin -o /mnt/crushmap.txt
  cat >>"${work}/crushmap.txt" <<_BW_CRUSH_EOF

rule ${rule} {
    id ${rid}
    type replicated
    step take default
    step choose firstn 0 type ${domain}
    step chooseleaf firstn ${replicas} type host
    step emit
}
_BW_CRUSH_EOF
  _bw_exec cephadm shell --mount "${work}:/mnt" -- crushtool -c /mnt/crushmap.txt -o /mnt/crushmap-new.bin
  _bw_exec ceph osd setcrushmap -i "${work}/crushmap-new.bin"
  rm -rf "${work}"
}

# _bw_exists <kind> <name>: return 0 when the resource already exists.
_bw_exists() {
  local kind="$1" name="$2"
  case "$kind" in
    ceph-pool)
      _bw_has_string "$(_bw_exec ceph osd pool ls --format json)" "$name" ;;
    ec-profile)
      _bw_has_string "$(_bw_exec ceph osd erasure-code-profile ls --format json)" "$name" ;;
    crush-rule)
      _bw_has_attr "$(_bw_exec ceph osd crush rule dump --format json)" rule_name "$name" ;;
    cephfs)
      _bw_has_attr "$(_bw_exec ceph fs ls --format json)" name "$name" ;;
    cephfs-subvolumegroup)
      local fs="${name%%/*}" grp="${name##*/}"
      _bw_has_attr "$(_bw_exec ceph fs subvolumegroup ls "$fs" --format json)" name "$grp" ;;
    mgr-module)
      jq -e --arg n "$name" '((.enabled_modules // []) + (.always_on_modules // [])) | any(. == $n)' \
        >/dev/null 2>&1 <<<"$(_bw_exec ceph mgr module ls --format json)" ;;
    stretch-mode)
      jq -e '.stretch_mode == true' >/dev/null 2>&1 <<<"$(_bw_exec ceph mon dump --format json)" ;;
    rgw-realm)
      _bw_exec radosgw-admin realm get --rgw-realm "$name" >/dev/null 2>&1 ;;
    rgw-zonegroup)
      _bw_exec radosgw-admin zonegroup get --rgw-zonegroup "$name" >/dev/null 2>&1 ;;
    rgw-zone)
      _bw_exec radosgw-admin zone get --rgw-zone "$name" >/dev/null 2>&1 ;;
    rgw-user)
      _bw_exec radosgw-admin user info --uid "$name" >/dev/null 2>&1 ;;
    nfs-export)
      local svc="${name%%|*}" pseudo="${name#*|}"
      _bw_exec ceph nfs export ls "$svc" --format json 2>/dev/null | jq -e --arg p "$pseudo" 'any(.[]; . == $p)' >/dev/null 2>&1 ;;
    *)
      return 1 ;;
  esac
}
`
