package ceph

import (
	"fmt"
	"strings"

	"github.com/crmarques/bootwright/api/v1alpha1"
	"github.com/crmarques/bootwright/internal/host/shellquote"
	"github.com/crmarques/bootwright/internal/storage/topology"
)

type CephScriptOptions struct {
	LibFile              string
	BootstrapConfFile    string
	BootstrapSpecFile    string
	CoreServicesSpecFile string
	LateServicesSpecFile string
	BootstrapImage       string
	AcceptLicense        bool
	IBMCallHome          string
}

func CephApplyScript(state v1alpha1.State, cluster v1alpha1.StorageCluster, opts CephScriptOptions) string {
	var b strings.Builder
	name := cluster.Metadata.Name

	b.WriteString("#!/usr/bin/env bash\n")
	fmt.Fprintf(&b, "# Generated by bootwright render for storage cluster %q. Do not edit.\n", name)
	b.WriteString("# Reproduces the Ceph objects bootwright configures from its input files\n")
	b.WriteString("# using native CLIs (cephadm / ceph / radosgw-admin / rbd) instead of\n")
	b.WriteString("# 'bootwright apply'. Re-runnable: create-style steps are guarded and\n")
	b.WriteString("# skip-if-exists; set-* steps reconcile in place. The data-destroying\n")
	b.WriteString("# --converge-drifted rebuild path is bootwright-only and is not generated here.\n")
	b.WriteString("set -euo pipefail\n")
	b.WriteString(`HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"` + "\n")
	b.WriteString("# shellcheck source=/dev/null\n")
	fmt.Fprintf(&b, "source \"$HERE/%s\"\n\n", opts.LibFile)

	writeBootstrapStage(&b, state, cluster, opts)

	b.WriteString("\necho \"== stage 10: host and core service specs (ceph orch apply) ==\"\n")
	writeOrchApply(&b, opts.BootstrapSpecFile)
	writeOrchApply(&b, opts.CoreServicesSpecFile)

	b.WriteString("\necho \"== stage 20: ceph objects ==\"\n")
	var lateOps []map[string]any
	for _, op := range cephOperationList(state, cluster) {
		if op["phase"] == "object-gateway" || op["phase"] == "late-topology" {
			lateOps = append(lateOps, op)
			continue
		}
		writeOperation(&b, op)
	}

	b.WriteString("\necho \"== stage 30: late service specs (ceph orch apply) ==\"\n")
	writeOrchApply(&b, opts.LateServicesSpecFile)

	if len(lateOps) > 0 {
		b.WriteString("\necho \"== stage 40: late objects (after the rgw/nfs services above) ==\"\n")
		for _, op := range lateOps {
			writeOperation(&b, op)
		}
	}

	if ManagementHasSecrets(cluster) {
		b.WriteString("\necho \"  [todo] spec.ceph.management carries TLS/oauth2-proxy secrets: the mgmt-gateway is NOT in this bundle.\"\n")
		b.WriteString("echo \"  [todo] The keepalive ingress above fronts it, so its VIP has no backend until you apply the\"\n")
		b.WriteString("echo \"  [todo] mgmt-gateway spec with your cert/secret files (or run 'bootwright apply --clusters <cluster>').\"\n")
	}

	fmt.Fprintf(&b, "\necho \"bootwright: ceph apply complete for %s\"\n", name)
	return b.String()
}

func cephOperationList(state v1alpha1.State, cluster v1alpha1.StorageCluster) []map[string]any {
	ops, _ := CephOperations(state, cluster)["operations"].([]map[string]any)
	return ops
}

func writeOrchApply(b *strings.Builder, file string) {
	if file == "" {
		return
	}
	fmt.Fprintf(b, "bw_run ceph orch apply -i \"$HERE/%s\"\n", file)
}

func writeBootstrapStage(b *strings.Builder, state v1alpha1.State, cluster v1alpha1.StorageCluster, opts CephScriptOptions) {
	ceph := cluster.Spec.Ceph
	args := []string{"cephadm"}
	if opts.BootstrapImage != "" {
		args = append(args, "--image", opts.BootstrapImage)
	}
	args = append(args,
		"bootstrap",
		"--mon-ip", topology.NodeAddressByRef(state, cluster, ceph.Cephadm.Bootstrap.Node, ceph.Cephadm.Bootstrap.AddressRef.Name),
		"--allow-fqdn-hostname",
		"--dashboard-password-noupdate",
	)
	if ceph.Cephadm.Bootstrap.SingleHostDefaults {
		args = append(args, "--single-host-defaults")
	}
	if opts.AcceptLicense {
		args = append(args, "--automatically-accept-license")
	}
	if cidrs := ceph.Networks.ClusterCIDRs; len(cidrs) > 0 {
		args = append(args, "--cluster-network", strings.Join(cidrs, ","))
	}
	if !MonitoringEnabled(cluster) {
		args = append(args, "--skip-monitoring-stack")
	}

	b.WriteString("echo \"== stage 00: cephadm bootstrap ==\"\n")
	b.WriteString("if [[ -f /etc/ceph/ceph.conf ]]; then\n")
	b.WriteString("  echo \"  [skip] cephadm bootstrap: /etc/ceph/ceph.conf present\"\n")
	b.WriteString("else\n")
	fmt.Fprintf(b, "  bootstrap=(%s", shellquote.Quote(args))
	if opts.BootstrapConfFile != "" {
		fmt.Fprintf(b, " --config \"$HERE/%s\"", opts.BootstrapConfFile)
	}
	b.WriteString(")\n")
	b.WriteString("  # Extra bootstrap-subcommand flags from the environment, e.g.\n")
	b.WriteString("  # --registry-json <file> for authenticated Red Hat / IBM registries.\n")
	b.WriteString("  # shellcheck disable=SC2206\n")
	b.WriteString("  [[ -n \"${BW_CEPHADM_BOOTSTRAP_EXTRA:-}\" ]] && bootstrap+=(${BW_CEPHADM_BOOTSTRAP_EXTRA})\n")
	b.WriteString("  bw_run \"${bootstrap[@]}\"\n")
	b.WriteString("fi\n")
	writeIBMCallHomeStage(b, opts.IBMCallHome)
}

func writeIBMCallHomeStage(b *strings.Builder, intent string) {
	if intent == "" {
		return
	}
	b.WriteString("\necho \"== stage 05: IBM Call Home ==\"\n")
	switch intent {
	case v1alpha1.StorageCephIBMCallHomeEnabled:
		b.WriteString("ibm_call_home_modules=\"$(_bw_exec ceph mgr module ls --format json)\"\n")
		b.WriteString("ibm_call_home_enabled=\"$(jq -r '(.enabled_modules // []) | index(\"call_home_agent\") != null' <<<\"$ibm_call_home_modules\")\"\n")
		b.WriteString("if [[ \"$ibm_call_home_enabled\" != \"true\" ]]; then\n")
		b.WriteString("  bw_run ceph mgr module enable call_home_agent\n")
		b.WriteString("fi\n")
		b.WriteString("bw_run ceph orch accept call-home-enabled\n")
	case v1alpha1.StorageCephIBMCallHomeDisabled:
		b.WriteString("bw_run ceph orch deny call-home-enabled\n")
	}
}

func writeOperation(b *strings.Builder, op map[string]any) {
	name := opString(op, "name")
	cmd := opCommand(op)
	kind, resName, guarded := opIdempotency(op)
	fmt.Fprintf(b, "# %s\n", name)
	if len(cmd) == 0 {
		if kind == "stretch-crush-rule" {
			domain, replicas := stretchRuleParams(op)
			fmt.Fprintf(b, "bw_stretch_crush_rule %s\n", shellquote.QuoteWords([]string{resName, domain, replicas}))
			return
		}
		if kind == "stretch-internal-pools" {
			rule, size, minSize, pattern := stretchInternalPoolParams(op)
			fmt.Fprintf(b, "bw_stretch_internal_pools %s\n", shellquote.QuoteWords([]string{rule, size, minSize, pattern}))
			return
		}
		fmt.Fprintf(b, "echo \"  [todo] %s cannot be expressed as a native command; apply it with 'bootwright apply --clusters <cluster>'\"\n", name)
		return
	}
	if stdin := opString(op, "stdin"); stdin != "" {
		fmt.Fprintf(b, "bw_run %s <<'BW_STDIN'\n%s\nBW_STDIN\n", shellquote.QuoteWords(cmd), stdin)
		return
	}
	sensitive := opSensitive(op)
	switch {
	case guarded && sensitive:
		fmt.Fprintf(b, "bw_guarded_quiet %s\n", shellquote.QuoteWords(append([]string{kind, resName, name}, cmd...)))
	case guarded:
		fmt.Fprintf(b, "bw_guarded %s\n", shellquote.QuoteWords(append([]string{kind, resName}, cmd...)))
	case sensitive:
		fmt.Fprintf(b, "bw_run_quiet %s\n", shellquote.QuoteWords(append([]string{name}, cmd...)))
	default:
		fmt.Fprintf(b, "bw_run %s\n", shellquote.QuoteWords(cmd))
	}
}

func stretchRuleParams(op map[string]any) (domain, replicas string) {
	replicas = "2"
	if s, ok := op["structural"].(map[string]any); ok {
		domain, _ = s["failureDomain"].(string)
		if r, ok := s["replicasPerFailureDomain"]; ok {
			replicas = fmt.Sprint(r)
		}
	}
	return domain, replicas
}

func stretchInternalPoolParams(op map[string]any) (rule, size, minSize, pattern string) {
	s, ok := op["structural"].(map[string]any)
	if !ok {
		return "", "", "", ""
	}
	rule, _ = s["ruleName"].(string)
	pattern, _ = s["poolPattern"].(string)
	return rule, fmt.Sprint(s["size"]), fmt.Sprint(s["minSize"]), pattern
}

func opString(op map[string]any, key string) string {
	if v, ok := op[key].(string); ok {
		return v
	}
	return ""
}

func opCommand(op map[string]any) []string {
	if cmd, ok := op["command"].([]string); ok {
		return cmd
	}
	return nil
}

func opIdempotency(op map[string]any) (kind, name string, ok bool) {
	m, has := op["idempotency"].(map[string]any)
	if !has {
		return "", "", false
	}
	kind, _ = m["kind"].(string)
	name, _ = m["name"].(string)
	return kind, name, kind != ""
}

func opSensitive(op map[string]any) bool {
	if nolog, ok := op["no_log"].(bool); ok && nolog {
		return true
	}
	_, hasCapture := op["capture"]
	return hasCapture
}
