package ceph

func CephApplyLib() string {
	return cephApplyLib
}

const cephApplyLib = `#!/usr/bin/env bash
# Generated by bootwright render. Do not edit.
#
# Shared helpers for the per-cluster Ceph apply script (apply.sh). Each guard
# mirrors the idempotency probe bootwright's apply role uses, so re-running
# apply.sh converges instead of erroring on already-created objects.
#
# Execution model: commands run where the Ceph admin keyring is available --
# normally ON the cephadm bootstrap host after 'cephadm bootstrap'. To target a
# remote or containerized CLI, export BW_CEPH_PREFIX, e.g.
#   export BW_CEPH_PREFIX="cephadm shell --"
#   export BW_CEPH_PREFIX="ssh root@mon-a --"
# It is word-split and prepended to every native invocation.

set -euo pipefail

if ! command -v jq >/dev/null 2>&1; then
  echo "bootwright: 'jq' is required by the idempotency guards but is not on PATH" >&2
  exit 1
fi

# shellcheck disable=SC2206
_bw_prefix=(${BW_CEPH_PREFIX:-})

# _bw_exec <argv...>: run a native command through the optional exec prefix.
_bw_exec() { "${_bw_prefix[@]}" "$@"; }

# bw_run <argv...>: run an in-place reconcile (idempotent) command.
bw_run() {
  echo "  [run ] $*"
  _bw_exec "$@"
}

# bw_run_quiet <label> <argv...>: run a command whose OUTPUT is sensitive (auth
# keys); the command line label is shown but stdout is discarded.
bw_run_quiet() {
  local label="$1"; shift
  echo "  [run ] ${label} (output redacted)"
  _bw_exec "$@" >/dev/null
}

# bw_guarded <kind> <name> <argv...>: run a create-style command unless the
# resource already exists (existence probe keyed by <kind>).
bw_guarded() {
  local kind="$1" name="$2"; shift 2
  if _bw_exists "$kind" "$name"; then
    echo "  [skip] ${kind} '${name}' already present"
    return 0
  fi
  echo "  [run ] $*"
  _bw_exec "$@"
}

# bw_guarded_quiet <kind> <name> <label> <argv...>: guarded, sensitive output
# discarded.
bw_guarded_quiet() {
  local kind="$1" name="$2" label="$3"; shift 3
  if _bw_exists "$kind" "$name"; then
    echo "  [skip] ${kind} '${name}' already present"
    return 0
  fi
  echo "  [run ] ${label} (output redacted)"
  _bw_exec "$@" >/dev/null
}

_bw_has_string() { jq -e --arg n "$2" 'any(.[]; . == $n)' >/dev/null 2>&1 <<<"$1"; }
_bw_has_attr() { jq -e --arg a "$2" --arg n "$3" 'any(.[]; .[$a] == $n)' >/dev/null 2>&1 <<<"$1"; }

# bw_stretch_crush_rule <rule> <failure-domain> <replicas-per-domain>: create the
# stretch CRUSH rule (two replicas per failure domain) that the enable-stretch and
# pool-crush-rule steps depend on. 'ceph osd crush rule create-replicated' cannot
# express the two-step rule, so it is compiled into the CRUSH map. crushtool is
# not on the host, so the de/compile steps run inside 'cephadm shell'. No-op if
# the rule already exists. Must run as root on the bootstrap host.
bw_stretch_crush_rule() {
  local rule="$1" domain="$2" replicas="$3"
  if _bw_has_attr "$(_bw_exec ceph osd crush rule dump --format json)" rule_name "$rule"; then
    echo "  [skip] crush-rule '${rule}' already present"
    return 0
  fi
  echo "  [run ] compile stretch CRUSH rule '${rule}'"
  local work rid
  work="$(mktemp -d)"
  rid="$(_bw_exec ceph osd crush rule dump --format json | jq '([.[].rule_id] + [0]) | max + 1')"
  _bw_exec ceph osd getcrushmap -o "${work}/crushmap.bin"
  _bw_exec cephadm shell --mount "${work}:/mnt" -- crushtool -d /mnt/crushmap.bin -o /mnt/crushmap.txt
  cat >>"${work}/crushmap.txt" <<_BW_CRUSH_EOF

rule ${rule} {
    id ${rid}
    type replicated
    step take default
    step choose firstn 0 type ${domain}
    step chooseleaf firstn ${replicas} type host
    step emit
}
_BW_CRUSH_EOF
  _bw_exec cephadm shell --mount "${work}:/mnt" -- crushtool -c /mnt/crushmap.txt -o /mnt/crushmap-new.bin
  _bw_exec ceph osd setcrushmap -i "${work}/crushmap-new.bin"
  rm -rf "${work}"
}

# bw_stretch_internal_pools <rule> <size> <min-size> <name-regex>: put the Ceph
# pools nobody declares (.mgr, .nfs, device_health_metrics, the rgw metadata
# pools) on the stretch placement. 'ceph mon enable_stretch_mode' re-homes every
# pool itself, but an arbiter-less stretch cluster never reaches that call and a
# pool created after it (rgw creates its pools when the first daemon starts)
# misses it too, so those pools would keep the default host rule at size 3 and
# go below min_size when a whole data site fails. Reconciles in place; matches
# nothing when the rgw daemons have not created their pools yet.
bw_stretch_internal_pools() {
  local rule="$1" size="$2" min_size="$3" pattern="$4" pool
  local pools
  pools="$(_bw_exec ceph osd pool ls detail --format json \
    | jq -r --arg re "$pattern" '.[] | select(.type == 1) | .pool_name | select(test($re))')"
  if [[ -z "$pools" ]]; then
    echo "  [skip] no internal pool matches '${pattern}' yet"
    return 0
  fi
  while read -r pool; do
    [[ -n "$pool" ]] || continue
    echo "  [run ] place internal pool '${pool}' on ${rule} (size ${size}, min_size ${min_size})"
    _bw_exec ceph osd pool set "$pool" crush_rule "$rule"
    _bw_exec ceph osd pool set "$pool" size "$size"
    _bw_exec ceph osd pool set "$pool" min_size "$min_size"
  done <<<"$pools"
}

# _bw_exists <kind> <name>: return 0 when the resource already exists.
_bw_exists() {
  local kind="$1" name="$2"
  case "$kind" in
    ceph-pool)
      _bw_has_string "$(_bw_exec ceph osd pool ls --format json)" "$name" ;;
    ec-profile)
      _bw_has_string "$(_bw_exec ceph osd erasure-code-profile ls --format json)" "$name" ;;
    crush-rule)
      _bw_has_attr "$(_bw_exec ceph osd crush rule dump --format json)" rule_name "$name" ;;
    cephfs)
      _bw_has_attr "$(_bw_exec ceph fs ls --format json)" name "$name" ;;
    cephfs-subvolumegroup)
      local fs="${name%%/*}" grp="${name##*/}"
      _bw_has_attr "$(_bw_exec ceph fs subvolumegroup ls "$fs" --format json)" name "$grp" ;;
    stretch-mode)
      jq -e '.stretch_mode == true' >/dev/null 2>&1 <<<"$(_bw_exec ceph mon dump --format json)" ;;
    rgw-realm)
      _bw_exec radosgw-admin realm get --rgw-realm "$name" >/dev/null 2>&1 ;;
    rgw-zonegroup)
      _bw_exec radosgw-admin zonegroup get --rgw-zonegroup "$name" >/dev/null 2>&1 ;;
    rgw-zone)
      _bw_exec radosgw-admin zone get --rgw-zone "$name" >/dev/null 2>&1 ;;
    rgw-user)
      _bw_exec radosgw-admin user info --uid "$name" >/dev/null 2>&1 ;;
    *)
      return 1 ;;
  esac
}
`
