apiVersion: bootwright.io/v1alpha1
kind: Machine
metadata:
  name: ceph-dc1-0
spec:
  capabilities:
    - ceph-node

  os:
    provided: true

  addresses:
    - name: ssh
      address: 192.168.141.30

  access:
    ssh:
      user: root
      keyRef: ceph-storage-cluster-admin-ssh-key
      addressRef: ssh
