apiVersion: bootwright.io/v1alpha1
kind: Secret
metadata:
  name: ceph-cluster-ssh
spec:
  type: sshKeyPair

  source:
    generated:
      comment: bootwright-ceph-cluster
---
apiVersion: bootwright.io/v1alpha1
kind: Secret
metadata:
  name: ceph-node-ssh
spec:
  type: sshKeyPair

  source:
    file:
      privateKey: ~/.ssh/bootwright-ssh-key
