apiVersion: bootwright.io/v1alpha1
kind: StorageCluster
metadata:
  name: ceph-oss
spec:
  type: ceph

  ceph:
    distribution: oss
    release: squid
    community:
      mirror: https://download.ceph.com
    cephadm:
      bootstrap:
        host: ceph-0
    topology:
      hosts:
        - machineRef: ceph-0
          roles:
            - mon
