apiVersion: bootwright.io/v1alpha1
kind: StorageCluster
metadata:
  name: ceph-oss
spec:
  type: ceph

  ceph:
    distribution: oss
    release: "20.2.2"
    community:
      mirror: https://download.ceph.com
    cephadm:
      bootstrap:
        node: node-01
    topology:
      nodes:
        - name: node-01
          machineRef: ceph-0
          roles:
            - mon
