apiVersion: bootwright.io/v1alpha1
kind: Environment
metadata:
  name: ceph-distribution-ibm
spec:
  baseDomain: bootwright.test

  secrets:
    - ceph-node-ssh:
        generated:
          sshKeyPair:
            comment: bootwright-ceph-node
    - ibm-rhsm-org
    - ibm-rhsm-activation-key
    - ibm-registry-credentials
