apiVersion: bootwright.io/v1alpha1
kind: Secret
metadata:
  name: ceph-cluster-ssh
spec:
  type: sshKeyPair

  source:
    generated:
      comment: bootwright-ceph-cluster
---
apiVersion: bootwright.io/v1alpha1
kind: Secret
metadata:
  name: ceph-node-ssh
spec:
  type: sshKeyPair

  source:
    file:
      privateKey: ~/.ssh/bootwright-ssh-key
---
apiVersion: bootwright.io/v1alpha1
kind: Secret
metadata:
  name: ibm-rhsm-org
spec:
  type: opaque
---
apiVersion: bootwright.io/v1alpha1
kind: Secret
metadata:
  name: ibm-rhsm-activation-key
spec:
  type: opaque
---
apiVersion: bootwright.io/v1alpha1
kind: Secret
metadata:
  name: ibm-registry-credentials
spec:
  type: usernamePassword
