apiVersion: bootwright.io/v1alpha1
kind: StorageCluster
metadata:
  name: ceph-ibm
spec:
  type: ceph

  ceph:
    distribution: ibm
    release: "9.9.0.3"
    packageVersion: "20.1.0-221.el9cp"
    image:
      version: "v9.0-20201"
    ibm:
      callHome: disabled
    entitlementRef: ibm-storage-ceph
    osSubscriptionRef: rhel
    cephadm:
      clusterSSH:
        keyRef: ceph-cluster-ssh
      bootstrap:
        node: node-01
    topology:
      nodes:
        - name: node-01
          machineRef: ceph-0
          roles:
            - mon
