apiVersion: bootwright.io/v1alpha1
kind: ClusterInfra
metadata:
  name: metal-ocp
spec:
  platform:
    type: baremetal
    baremetal:
      provisioningNetwork: disabled

  endpoints:
    api:
      externalVip: 192.168.150.10
    apiInt:
      externalVip: 192.168.150.10
    ingress:
      externalVip: 192.168.150.11

  components:
    machines:
      - name: master-0
        from:
          provider: baremetal-provider
          name: metal-master-0
        networkConfig:
          ref:
            name: metal-net
          addresses:
            - interface: primary
              ipv4:
                - ip: 192.168.150.20
                  prefix-length: 24
