apiVersion: bootwright.io/v1alpha1
kind: ClusterAddonBinding
metadata:
  name: ocp-multidc-02-addons
spec:
  clusterRef: ocp-multidc-02

  profileRefs:
    - physical-cluster-addons

  addonConfigs:
    - addonRef: fusion-data-foundation
      inputs:
        - name: external-storage
          value: ceph-multidc-01-odf-ocp-multidc-02
        - name: ibm-entitlement
          value: ibm-entitlement-key
