apiVersion: bootwright.io/v1alpha1
kind: ContainerCluster
metadata:
  name: sno-libvirt
spec:
  distribution:
    release:
      version: 4.21.15

  install:
    nodeSSH:
      keyPairRef: sno-libvirt-cluster-admin-ssh-key
    endpoints:
      api:
        address: 192.168.132.10
        source:
          type: external
      ingress:
        address: 192.168.132.11
        source:
          type: external

  hosts:

  - hostname: master-0
    role: master
    machineRef: sno-libvirt-master-0
