apiVersion: bootwright.io/v1alpha1
kind: Environment
metadata:
  name: sno-libvirt-redfish
spec:
  baseDomain: bootwright.test

  infraComponents:
    nameResolution:
      - name: default
        management: managed
        componentRef: name-resolution
