apiVersion: bootwright.io/v1alpha1
kind: Machine
metadata:
  name: hub-multidc-01-master-03

spec:
  capabilities:
    - openshift-node

  placement:
    site: site-a

  substrate:
    providerRef: kubevirt-ocp-multidc-01
    profileRef: general

  os:
    provided: false

  network:
    configRef: hub-vm-network

    interfaceAttachments:
      - interface: primary
        attachmentRef: hub-vm-machine

      - interface: ceph-public
        attachmentRef: hub-vm-ceph-public

    installAddressRef: ip

    addresses:
      - name: fqdn
        address: hub-multidc-01-master-03.example.com

      - name: ip
        address: 192.0.2.15/24
        interface: primary

      - name: ceph-public
        address: 198.51.100.33/25
        interface: ceph-public

    overrides: {}
