apiVersion: bootwright.io/v1alpha1
kind: InfraProvider
metadata:
  name: child-kubevirt-provider
spec:
  machineProfiles:
    - name: child-sno
      cpu: 8
      memoryMiB: 16384
      diskGiB: 120
      kubevirt:
        hostClusterRef:
          name: metal-ocp
        namespace: bootwright-child-ocp
        storageClassRef:
          name: lvms-vg1
