apiVersion: bootwright.io/v1alpha1
kind: ContainerCluster
metadata:
  name: sno-baremetal
spec:
  distribution:
    release:
      version: 4.21.15

  install:
    nodeSSH:
      keyPairRef: sno-baremetal-cluster-admin-ssh-key
    endpoints:
      api:
        address: 192.168.140.10
        source:
          type: external
      ingress:
        address: 192.168.140.11
        source:
          type: external
    artifactAccess:
      serverRef: default
      redfishVirtualMedia:
        endpointRef: bmc

  hosts:

  - hostname: master-0
    role: master
    machineRef: rack1-srv1
