apiVersion: bootwright.io/v1alpha1
kind: Environment
metadata:
  name: sno-baremetal-redfish
spec:
  baseDomain: bootwright.test

  infraComponents:
    artifactServers:
      - name: default
        management: managed
        componentRef: artifact-server
