apiVersion: bootwright.io/v1alpha1
kind: Secret
metadata:
  name: openshift-pull-secret
spec:
  type: dockerConfigJson
---
apiVersion: bootwright.io/v1alpha1
kind: Secret
metadata:
  name: sno-baremetal-cluster-admin-ssh-key
spec:
  type: sshKeyPair

  source:
    generated:
      comment: bootwright-sno-baremetal-cluster-admin
---
apiVersion: bootwright.io/v1alpha1
kind: Secret
metadata:
  name: bastion-host-ssh
spec:
  type: sshKeyPair

  source:
    file:
      privateKey: ~/.ssh/bootwright-ssh-key
---
apiVersion: bootwright.io/v1alpha1
kind: Secret
metadata:
  name: bmc-credentials
spec:
  type: usernamePassword

  source:
    generated:
      username: admin
