apiVersion: bootwright.io/v1alpha1
kind: Entitlement
metadata:
  name: rhcs
spec:
  type: redhat-ceph

  rhsm:
    organizationRef: redhat-org
    activationKeyRef: redhat-activation-key

  registry:
    credentialsRef: redhat-registry-credentials
