apiVersion: bootwright.io/v1alpha1
kind: Secret
metadata:
  name: ceph-node-ssh
spec:
  type: sshKeyPair

  source:
    generated:
      comment: bootwright-ceph-node
---
apiVersion: bootwright.io/v1alpha1
kind: Secret
metadata:
  name: redhat-org
spec:
  type: opaque
---
apiVersion: bootwright.io/v1alpha1
kind: Secret
metadata:
  name: redhat-activation-key
spec:
  type: opaque
---
apiVersion: bootwright.io/v1alpha1
kind: Secret
metadata:
  name: redhat-registry-credentials
spec:
  type: usernamePassword
