apiVersion: bootwright.io/v1alpha1
kind: StorageCluster
metadata:
  name: ceph-storage
spec:
  type: ceph

  ceph:
    distribution: redhat
    release: "9.1"
    entitlementRef: rhcs
    cephadm:
      clusterSSH:
        keyRef: ceph-cluster-ssh-key
      bootstrap:
        node: node-01
    networks:
      publicCIDRs:
      - 192.168.141.0/24
      - 192.168.142.0/24
      - 192.168.143.0/24
      clusterCIDRs:
      - 172.21.141.0/24
      - 172.21.142.0/24
    topology:
      stretch:
        failureDomain: datacenter
        tiebreaker:
          node: node-07
      nodes:
      - name: node-01
        machineRef: ceph-dc1-0
        roles:
        - mon
        - mgr
        - osd
        - mds
        - rgw
        - ingress
        devices:
        - /dev/sdb
      - name: node-02
        machineRef: ceph-dc1-1
        roles:
        - mon
        - mgr
        - osd
        - mds
        - rgw
        - ingress
        devices:
        - /dev/sdb
      - name: node-03
        machineRef: ceph-dc1-2
        roles:
        - osd
        - mds
        - rgw
        - ingress
        devices:
        - /dev/sdb
      - name: node-04
        machineRef: ceph-dc2-0
        roles:
        - mon
        - mgr
        - osd
        - mds
        - rgw
        - ingress
        devices:
        - /dev/sdb
      - name: node-05
        machineRef: ceph-dc2-1
        roles:
        - mon
        - mgr
        - osd
        - mds
        - rgw
        - ingress
        devices:
        - /dev/sdb
      - name: node-06
        machineRef: ceph-dc2-2
        roles:
        - osd
        - mds
        - rgw
        - ingress
        devices:
        - /dev/sdb
      - name: node-07
        machineRef: ceph-arbiter
        roles:
        - mon
