apiVersion: bootwright.io/v1alpha1
kind: StorageCluster
metadata:
  name: ceph-storage
spec:
  type: ceph

  ceph:
    distribution: redhat
    entitlementRef: rhcs
    cephadm:
      addressRef: ssh
      bootstrap:
        seedNode: ceph-dc1-0
        monIP:
          nodeRef: ceph-dc1-0
    networks:
      publicCIDRs:
      - 192.168.141.0/24
      - 192.168.142.0/24
      - 192.168.143.0/24
      clusterCIDRs:
      - 172.21.141.0/24
      - 172.21.142.0/24
    topology:
      stretch:
        enabled: true
        failureDomain: datacenter
        dataSites:
        - dc1
        - dc2
        tiebreaker:
          site: dc3
          node: ceph-arbiter
        replicatedPoolDefaults:
          size: 4
          minSize: 2
        ruleName: stretch-replicated
      nodes:
      - name: ceph-dc1-0
        site: dc1
        roles:
        - mon
        - mgr
        - osd
        - mds
        - rgw
        - ingress
        devices:
        - /dev/sdb
        machineRef: ceph-dc1-0
      - name: ceph-dc1-1
        site: dc1
        roles:
        - mon
        - mgr
        - osd
        - mds
        - rgw
        - ingress
        devices:
        - /dev/sdb
        machineRef: ceph-dc1-1
      - name: ceph-dc1-2
        site: dc1
        roles:
        - osd
        - mds
        - rgw
        - ingress
        devices:
        - /dev/sdb
        machineRef: ceph-dc1-2
      - name: ceph-dc2-0
        site: dc2
        roles:
        - mon
        - mgr
        - osd
        - mds
        - rgw
        - ingress
        devices:
        - /dev/sdb
        machineRef: ceph-dc2-0
      - name: ceph-dc2-1
        site: dc2
        roles:
        - mon
        - mgr
        - osd
        - mds
        - rgw
        - ingress
        devices:
        - /dev/sdb
        machineRef: ceph-dc2-1
      - name: ceph-dc2-2
        site: dc2
        roles:
        - osd
        - mds
        - rgw
        - ingress
        devices:
        - /dev/sdb
        machineRef: ceph-dc2-2
      - name: ceph-arbiter
        site: dc3
        roles:
        - mon
        machineRef: ceph-arbiter
