apiVersion: bootwright.io/v1alpha1
kind: StorageCluster
metadata:
  name: ceph-storage
spec:
  type: ceph

  ceph:
    distribution: redhat
    release: "9.1"
    entitlementRef: rhcs
    cephadm:
      bootstrap:
        host: ceph-dc1-0
    networks:
      publicCIDRs:
      - 192.168.141.0/24
      - 192.168.142.0/24
      - 192.168.143.0/24
      clusterCIDRs:
      - 172.21.141.0/24
      - 172.21.142.0/24
    topology:
      stretch:
        failureDomain: datacenter
        tiebreaker:
          host: ceph-arbiter
      hosts:
      - machineRef: ceph-dc1-0
        site: dc1
        roles:
        - mon
        - mgr
        - osd
        - mds
        - rgw
        - ingress
        devices:
        - /dev/sdb
      - machineRef: ceph-dc1-1
        site: dc1
        roles:
        - mon
        - mgr
        - osd
        - mds
        - rgw
        - ingress
        devices:
        - /dev/sdb
      - machineRef: ceph-dc1-2
        site: dc1
        roles:
        - osd
        - mds
        - rgw
        - ingress
        devices:
        - /dev/sdb
      - machineRef: ceph-dc2-0
        site: dc2
        roles:
        - mon
        - mgr
        - osd
        - mds
        - rgw
        - ingress
        devices:
        - /dev/sdb
      - machineRef: ceph-dc2-1
        site: dc2
        roles:
        - mon
        - mgr
        - osd
        - mds
        - rgw
        - ingress
        devices:
        - /dev/sdb
      - machineRef: ceph-dc2-2
        site: dc2
        roles:
        - osd
        - mds
        - rgw
        - ingress
        devices:
        - /dev/sdb
      - machineRef: ceph-arbiter
        site: dc3
        roles:
        - mon
