apiVersion: bootwright.io/v1alpha1
kind: InfraProvider
metadata:
  name: kubevirt-ocp-multidc-02

spec:
  kubevirt:
    hostClusterRef: ocp-multidc-02
    namespace: bootwright-multidc-virtual-clusters
    storageClassRef: ocs-external-storagecluster-ceph-rbd
    machineProfiles:
      - name: general
        cpu: 4
        memoryMiB: 16384
        diskGiB: 100
        tpm:
          persistent: true

      - name: large
        cpu: 8
        memoryMiB: 32768
        diskGiB: 160
        tpm:
          persistent: true

  networkAttachments:
    - name: hub-vm-machine
      kubevirt:
        networkRef:
          apiGroup: k8s.ovn.org
          kind: ClusterUserDefinedNetwork
          name: multidc-virtual-cluster-machine

    - name: hub-vm-ceph-public
      kubevirt:
        networkRef:
          apiGroup: k8s.ovn.org
          kind: ClusterUserDefinedNetwork
          name: multidc-virtual-cluster-ceph-public
