apiVersion: bootwright.io/v1alpha1
kind: Machine
metadata:
  name: ceph-3
spec:
  capabilities:
    - ceph-node

  substrate:
    providerRef: lab-libvirt-provider
    profileRef: ceph-mon

  os:
    provided: false
    installProfileRef: rhel-9-ceph-node
    install:
      rootDeviceHints:
        deviceName: /dev/vda

  network:
    config:
      networkConfigRef: ceph-bridge
      attachmentRef: ceph-bridge
      interfaceAddresses:
        - interface: primary
          addressRef: ssh
          prefixLength: 24

  addresses:
    - name: ssh
      address: 192.168.140.23

  access:
    ssh:
      user: root
      keyRef: ceph-node-ssh
      addressRef: ssh
