apiVersion: bootwright.io/v1alpha1
kind: StorageFilesystem
metadata:
  name: cephfs
spec:
  storageClusterRef: ceph-ibm

  cephfs:
    metadataPoolRef: cephfs-metadata
    dataPoolRefs:
      - name: cephfs-data
        default: true
    mds:
      activeCount: 1
      placement:
        hosts:
          - node-01
          - node-02
