package installation

import (
	"net/netip"
	"slices"
	"strconv"
	"strings"

	"github.com/crmarques/bootwright/internal/substrate"
)

const kickstartVersion = "kickstart-anaconda-v4"

// hostKeySource is the key the installation republishes. Ed25519 is the type
// the identity operation binds, and generating it here rather than at first
// boot means the published copy is the key sshd will actually present.
const hostKeySource = "/etc/ssh/ssh_host_ed25519_key.pub"

// agentFilter is the guest agent's RPC filter, and identityRPCs are the
// commands the identity operation reads a bounded guest file through. RHEL
// ships an allow list that omits all three, so an installation that left the
// filter alone would complete and then prove nothing.
const (
	agentFilter  = "/etc/sysconfig/qemu-ga"
	identityRPCs = "guest-file-open,guest-file-close,guest-file-read"
)

// PrivateURLToken and CertificateToken are substituted at execution like the
// two below. The private URL carries the unguessable segment the attempt mints,
// so it is never frozen in the plan, and the certificate is the public half of
// the artifact server's own, which the installer verifies the fetch against.
const (
	PrivateURLToken  = "@@BOOTWRIGHT_PRIVATE_URL@@"
	CertificateToken = "@@BOOTWRIGHT_ARTIFACT_CERTIFICATE@@"
)

// MarkerToken and AuthorizedKeyToken are the two values the adapter substitutes
// into the frozen Kickstart at render time. Both are derived at execution: the
// marker names the request digest, which is the digest of the request that
// carries the Kickstart, and the authorized key comes from a bound Secret. The
// substitution is the adapter's only edit, and neither value is secret.
const (
	MarkerToken        = "@@BOOTWRIGHT_MARKER@@"
	AuthorizedKeyToken = "@@BOOTWRIGHT_AUTHORIZED_KEY@@"
)

// Repository is one repository the installed system configures.
type Repository struct {
	BaseURL string
	Enabled bool
	ID      string
}

// Installation is everything the Kickstart is derived from. Every field comes
// from effective state alone, so two compilations of one revision render the
// same bytes.
type Installation struct {
	Address          string
	AdditionalLocale []string
	// Channel is the identity channel this machine will answer on, which
	// decides what the %post has to establish for it to answer at all.
	Channel string
	// ExpectedMACs and Physical belong to operator-owned hardware: the
	// installer proves it is running on the machine the declaration names
	// before it erases anything.
	ExpectedMACs []string
	Physical     bool
	// InterfaceMAC addresses the installation interface by hardware address
	// rather than by a kernel name the booted installer may not reproduce.
	InterfaceMAC     string
	DisabledServices []string
	EnabledServices  []string
	ExcludeDocs      bool
	Firewall         string
	Formats          string
	Gateway          string
	HostKeyPath      string
	Hostname         string
	Interface        string
	Keyboard         string
	Language         string
	MarkerPath       string
	Nameservers      []string
	NTPServers       []string
	Packages         []string
	PackageSource    string
	Prefix           int
	Repositories     []Repository
	RootDevice       string
	SELinux          string
	Timezone         string
	User             string
	WeakDeps         string
}

// RenderKickstart derives the complete unattended installation. The machine
// powers off when it is done, so the controller ejects the media and boots the
// installed system from disk deliberately rather than racing a reboot. It
// writes no secret: the account is authorized by a public key the adapter substitutes,
// the root account is locked, and the %post removes every retained copy of the
// file so the installed system keeps none.
func RenderKickstart(input Installation) (string, error) {
	network, err := networkLine(input)
	if err != nil {
		return "", err
	}
	lines := []string{
		"# Generated by Bootwright. Do not edit.",
		"text",
		"eula --agreed",
		"poweroff",
		"",
		input.PackageSource,
		network,
		"",
		"lang " + input.Language + languageSuffix(input),
		"keyboard --vckeymap=" + input.Keyboard,
		timezoneLine(input),
		"",
		"rootpw --lock",
		"user --name=" + input.User + " --groups=wheel --lock",
		`sshkey --username=` + input.User + ` "` + AuthorizedKeyToken + `"`,
		"",
	}
	lines = append(lines, targetProofLines(input)...)
	lines = append(lines, storageLines(input)...)
	lines = append(lines, "")
	lines = append(lines, securityLines(input)...)
	lines = append(lines, "", servicesLine(input))
	for _, repository := range input.Repositories {
		lines = append(lines, repositoryLine(repository))
	}
	lines = append(lines, "")
	lines = append(lines, packagesSection(input)...)
	lines = append(lines, "")
	lines = append(lines, postSection(input)...)
	return strings.Join(compact(lines), "\n") + "\n", nil
}

// networkLine is the one static assignment the installer applies, from the
// Machine's own selected install address and its network's default route.
func networkLine(input Installation) (string, error) {
	address, err := netip.ParseAddr(input.Address)
	if err != nil || !address.Is4() {
		return "", refusal("api.value", "the Machine's install address is not an IPv4 literal", "correct the selected install address")
	}
	if input.Prefix < 1 || input.Prefix > 32 {
		return "", refusal("api.value", "the Machine's install address carries no usable prefix", "correct the selected install address")
	}
	device := input.Interface
	if input.InterfaceMAC != "" {
		device = input.InterfaceMAC
	}
	fields := []string{
		"network", "--bootproto=static", "--device=" + device,
		"--ip=" + input.Address, "--netmask=" + netmask(input.Prefix),
		"--hostname=" + input.Hostname, "--onboot=on", "--activate",
	}
	if input.Gateway != "" {
		fields = append(fields, "--gateway="+input.Gateway)
	}
	if len(input.Nameservers) != 0 {
		fields = append(fields, "--nameserver="+strings.Join(input.Nameservers, ","))
	}
	return strings.Join(fields, " "), nil
}

func netmask(prefix int) string {
	bits := ^uint32(0) << (32 - prefix)
	parts := make([]string, 0, 4)
	for shift := 24; shift >= 0; shift -= 8 {
		parts = append(parts, strconv.Itoa(int(bits>>uint(shift)&0xff)))
	}
	return strings.Join(parts, ".")
}

func languageSuffix(input Installation) string {
	if len(input.AdditionalLocale) == 0 {
		return ""
	}
	return " --addsupport=" + strings.Join(input.AdditionalLocale, ",")
}

func timezoneLine(input Installation) string {
	line := "timezone " + input.Timezone + " --utc"
	if len(input.NTPServers) != 0 {
		line += " --ntpservers=" + strings.Join(input.NTPServers, ",")
	}
	return line
}

// storageLines clear and partition exactly the named device, or leave the
// installer to choose when the Machine names none.
func storageLines(input Installation) []string {
	if input.RootDevice == "" {
		return []string{"clearpart --all --initlabel", "autopart --type=lvm"}
	}
	device := strings.TrimPrefix(input.RootDevice, "/dev/")
	return []string{
		"ignoredisk --only-use=" + device,
		"clearpart --all --initlabel --drives=" + device,
		"autopart --type=lvm",
	}
}

func securityLines(input Installation) []string {
	var lines []string
	if input.SELinux != "" {
		lines = append(lines, "selinux --"+input.SELinux)
	}
	if input.Firewall != "" {
		lines = append(lines, "firewall --"+input.Firewall)
	}
	return lines
}

func servicesLine(input Installation) string {
	fields := []string{"services"}
	if len(input.EnabledServices) != 0 {
		fields = append(fields, "--enabled="+strings.Join(input.EnabledServices, ","))
	}
	if len(input.DisabledServices) != 0 {
		fields = append(fields, "--disabled="+strings.Join(input.DisabledServices, ","))
	}
	if len(fields) == 1 {
		return ""
	}
	return strings.Join(fields, " ")
}

// repositoryLine installs one configured repository into the installed system.
// A disabled declaration configures nothing, because Anaconda has no form for
// a repository it must not use.
func repositoryLine(repository Repository) string {
	if !repository.Enabled {
		return ""
	}
	return strings.Join([]string{"repo", "--name=" + repository.ID, "--baseurl=" + repository.BaseURL, "--install"}, " ")
}

func packagesSection(input Installation) []string {
	header := "%packages"
	if input.ExcludeDocs {
		header += " --excludedocs"
	}
	if input.WeakDeps != "" {
		header += " " + input.WeakDeps
	}
	lines := []string{header, "@^minimal-environment"}
	lines = append(lines, input.Packages...)
	return append(lines, "%end")
}

// postSection writes the install marker, the account's passwordless escalation,
// the daemon policy and the guest agent's RPC filter, then removes every
// retained copy of the Kickstart so the installed system keeps none.
func postSection(input Installation) []string {
	lines := []string{
		"%post --erroronfail",
		"set -eu",
		"install -d -m 0755 " + parentOf(input.MarkerPath),
		"cat > " + input.MarkerPath + " <<'BOOTWRIGHT_MARKER_EOF'",
		MarkerToken,
		"BOOTWRIGHT_MARKER_EOF",
		"chmod 0444 " + input.MarkerPath,
	}
	lines = append(lines, identityLines(input)...)
	lines = append(lines, []string{
		"install -d -m 0750 /etc/sudoers.d",
		"printf '%s\\n' '" + input.User + " ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/60-bootwright",
		"chmod 0440 /etc/sudoers.d/60-bootwright",
		"install -d -m 0755 /etc/ssh/sshd_config.d",
		"printf '%s\\n' 'PasswordAuthentication no' 'PermitRootLogin prohibit-password' > /etc/ssh/sshd_config.d/60-bootwright.conf",
		"chmod 0600 /etc/ssh/sshd_config.d/60-bootwright.conf",
	}...)
	return append(lines,
		"rm -f /root/anaconda-ks.cfg /root/original-ks.cfg /run/install/ks.cfg",
		"%end",
	)
}

// identityLines establish whatever the machine's own identity channel needs in
// order to answer once the installation is over. A guest agent reads files the
// installation wrote, so the key is generated and republished where the agent
// may reach it and the agent is permitted those reads; a delivered key is
// installed as sshd's own before any key is generated, so the machine presents
// exactly the key that was frozen with the plan.
func identityLines(input Installation) []string {
	if input.Channel == substrate.ChannelDeliveredKey {
		return deliveredKeyLines()
	}
	if input.Channel != substrate.ChannelGuestAgent {
		return nil
	}
	return append([]string{
		"/usr/bin/ssh-keygen -A",
		"install -m 0444 " + hostKeySource + " " + input.HostKeyPath,
		"test -s " + input.HostKeyPath,
	}, agentFilterLines()...)
}

// deliveredKeyLines install the key pair this installation was given as the
// machine's own, before any key is generated, so `ssh-keygen -A` adds only the
// types it did not receive and the machine presents exactly the key the plan
// froze. The fetch verifies the server's certificate rather than disabling
// verification, because the confidentiality of the path depends on it, and the
// material is removed from the installer environment as soon as it is placed.
func deliveredKeyLines() []string {
	return []string{
		"install -d -m 0755 /etc/ssh",
		"cat > /tmp/bootwright-artifact-ca.pem <<'BOOTWRIGHT_ARTIFACT_CA_EOF'",
		CertificateToken,
		"BOOTWRIGHT_ARTIFACT_CA_EOF",
		"curl --fail --silent --show-error --cacert /tmp/bootwright-artifact-ca.pem" +
			" --output /etc/ssh/ssh_host_ed25519_key '" + PrivateURLToken + "/" + IdentityFile + "'",
		"curl --fail --silent --show-error --cacert /tmp/bootwright-artifact-ca.pem" +
			" --output /etc/ssh/ssh_host_ed25519_key.pub '" + PrivateURLToken + "/" + IdentityFile + ".pub'",
		"chmod 0600 /etc/ssh/ssh_host_ed25519_key",
		"chmod 0644 /etc/ssh/ssh_host_ed25519_key.pub",
		"test -s /etc/ssh/ssh_host_ed25519_key",
		"/usr/bin/ssh-keygen -A",
		"/usr/bin/ssh-keygen -y -f /etc/ssh/ssh_host_ed25519_key > /dev/null",
		"shred -u /tmp/bootwright-artifact-ca.pem 2>/dev/null || rm -f /tmp/bootwright-artifact-ca.pem",
	}
}

// targetProofLines repeat the controller-side target proof on the machine that
// is actually running the installer. The controller's proof closes before the
// machine boots, and a machine can be re-cabled or re-addressed in between, so
// this is the last point at which the wrong server can still be stopped. It
// runs before any storage is touched and fails closed; no authorization
// relaxes it, because `data-loss` acknowledges a loss rather than selecting
// what to lose.
func targetProofLines(input Installation) []string {
	if !input.Physical || len(input.ExpectedMACs) == 0 {
		return nil
	}
	lines := []string{
		"%pre --erroronfail --interpreter=/bin/bash",
		"set -euo pipefail",
		`bootwright_observed=$(cat /sys/class/net/*/address | tr 'A-Z' 'a-z' | sort -u)`,
	}
	for _, address := range input.ExpectedMACs {
		lines = append(lines,
			`if ! printf '%s\n' "${bootwright_observed}" | grep -Fqx '`+address+`'; then`,
			`echo 'Bootwright: this machine does not report `+address+
				`, which its declaration requires; refusing before any disk is touched.' >&2`,
			"exit 1",
			"fi")
	}
	if input.RootDevice != "" {
		lines = append(lines,
			`bootwright_root=$(readlink -f -- '`+input.RootDevice+`' || true)`,
			`if [ -z "${bootwright_root}" ] || [ ! -b "${bootwright_root}" ]; then`,
			`echo 'Bootwright: the declared root device `+input.RootDevice+
				` is not a block device here; refusing before any disk is touched.' >&2`,
			"exit 1",
			"fi",
			`if [ "$(lsblk -ndo TYPE -- "${bootwright_root}")" != disk ]; then`,
			`echo 'Bootwright: the declared root device `+input.RootDevice+
				` is not a whole disk; refusing before any disk is touched.' >&2`,
			"exit 1",
			"fi")
	}
	return append(lines, "%end", "")
}

// agentFilterLines permit exactly the identity operation's reads and prove the
// edit took, so a release that spells the filter differently fails the
// installation rather than leaving a guest that can never prove completion.
func agentFilterLines() []string {
	return []string{
		`if grep -q '^FILTER_RPC_ARGS=.*--allow-rpcs=' ` + agentFilter + `; then`,
		`sed -i '/^FILTER_RPC_ARGS=/s/--allow-rpcs=/--allow-rpcs=` + identityRPCs + `,/' ` + agentFilter,
		`grep -q '^FILTER_RPC_ARGS=.*--allow-rpcs=` + identityRPCs + `,' ` + agentFilter,
		`elif grep -q '^FILTER_RPC_ARGS=.*--block-rpcs=' ` + agentFilter + `; then`,
		`sed -i '/^FILTER_RPC_ARGS=/s/guest-file-open,//;/^FILTER_RPC_ARGS=/s/guest-file-close,//;/^FILTER_RPC_ARGS=/s/guest-file-read,//' ` + agentFilter,
		`! grep -q '^FILTER_RPC_ARGS=.*guest-file-open' ` + agentFilter,
		`fi`,
	}
}

func parentOf(path string) string {
	index := strings.LastIndex(path, "/")
	if index <= 0 {
		return "/"
	}
	return path[:index]
}

// compact removes the empty strings an omitted directive leaves behind, and
// collapses the blank lines around them, so the rendered file is deterministic.
func compact(lines []string) []string {
	out := make([]string, 0, len(lines))
	for _, line := range lines {
		if line == "" && (len(out) == 0 || out[len(out)-1] == "") {
			continue
		}
		out = append(out, line)
	}
	for len(out) != 0 && out[len(out)-1] == "" {
		out = out[:len(out)-1]
	}
	return out
}

// SortedUnique is the canonical order every derived list carries, so one
// revision always renders one file.
func SortedUnique(values []string) []string {
	out := slices.Clone(values)
	slices.Sort(out)
	return slices.Compact(out)
}
