apiVersion: bootwright.io/v1alpha1
kind: Host
metadata:
  name: services-host
spec:
  addresses:
    - name: ssh
      address: 192.168.140.10
    - name: lab-lan
      address: 192.168.140.10

  ssh:
    addressName: ssh
    keyRef:
      name: provider-host-ssh

  capabilities:
    - container-runtime
