apiVersion: bootwright.io/v1alpha1
kind: Machine
metadata:
  name: bastion

spec:
  capabilities:
    - container-runtime

  os:
    provided: true

  proxy:
    proxyRef: default
    noProxy:
      - .example.com
      - 192.0.2.0/24
      - 198.51.100.0/24
      - 203.0.113.0/24

  network:
    addresses:
      - name: fqdn
        address: utility-01.example.com

      - name: dns-alias
        address: utility-01.example.com

      - name: ip
        address: 192.0.2.127

  access:
    local: true
    rootLogin: keep
