apiVersion: bootwright.io/v1alpha1
kind: StorageObjectGateway
metadata:
  name: odf-rgw-all

spec:
  clusterRef: ceph-multidc-01
  serviceID: odf.all

  placement:
    hosts:
      - node-01
      - node-02
      - node-03
      - node-04
      - node-05
      - node-06
    countPerHost: 1

  frontendPort: 8080
  config: {}

  endpoint:
    dnsLabel: rgw
    scheme: https
    port: 443

    tls:
      secretRef: ceph-multidc-01-rgw-all-tls

    ingresses:
      - name: ha
        address: 198.51.100.59
        prefixLength: 25
        virtualInterfaceNetworks:
          - "198.51.100.0/25"
        firstVirtualRouterID: 43
        placement:
          hosts:
            - node-01
            - node-02
            - node-03
            - node-04
            - node-05
            - node-06
