---
- name: Wait before reading the machine again
  ansible.builtin.command:
    argv:
      - /usr/bin/sleep
      - '{{ managedos_install_anaconda_identity_delay }}'
  changed_when: false

- name: Read the machine again
  ansible.builtin.include_tasks: identity.yml
