apiVersion: bootwright.io/v1alpha1
kind: Environment
metadata:
  name: sno-libvirt
spec:
  baseDomain: example.test

  resources:
    - shared/hosts.yaml
    - shared/networks.yaml
    - shared/provider.yaml
    - shared/infra-component.yaml
    - clusters/sno-libvirt/cluster-infra.yaml
    - clusters/sno-libvirt/container-cluster.yaml

  secrets:
    openshift-pull-secret: null
    cluster-admin-ssh-key:
      generated:
        sshKeyPair:
          type: ed25519
          comment: bootwright-cluster-admin
    provider-host-ssh:
      file: ~/.ssh/bootwright-ssh-key
    bmc-credentials:
      generated:
        credentials:
          username: admin
    proxy-credentials:
      generated:
        credentials:
          username: proxy

  infraComponents:
    proxies:
      - name: default
        default: true
        type: managed
        componentRef:
          name: proxy
    nameResolution:
      - name: default
        default: true
        type: managed
        componentRef:
          name: name-resolution

  proxyFor:
    bootwright: default
    clusterInstall: default
