---
- name: Resolve vSphere virtual media context
  ansible.builtin.import_tasks: context.yml

- name: Insert vSphere virtual media
  ansible.builtin.import_tasks: insert.yml

- name: Clean up vSphere virtual media
  ansible.builtin.import_tasks: cleanup.yml
