apiVersion: bootwright.io/v1alpha1
kind: Environment
metadata:
  name: baremetal-redfish-addons
spec:
  domains:
    base: bootwright.test

  resources:
    - secrets.yaml
    - infra
    - clusters
    - add-ons
    - playbooks-custom

  infraComponents:
    artifactServers:
      - name: default
        management: managed
        componentRef: artifact-server
