apiVersion: bootwright.io/v1alpha1
kind: Environment
metadata:
  name: baremetal-redfish-addons
spec:
  baseDomain: bootwright.test

  defaults:
    artifactAccess:
      serverRef: default
      redfishVirtualMedia:
        endpointRef: bmc

  resources:
    - secrets.yaml
    - infra
    - clusters
    - add-ons

  infraComponents:
    artifactServers:
      - name: default
        management: managed
        componentRef: artifact-server
