apiVersion: bootwright.io/v1alpha1
kind: StorageObjectGateway
metadata:
  name: odf-rgw
spec:
  storageClusterRef: ceph-storage

  public:
    dnsLabel: rgw-ceph
    scheme: https
    port: 443

  ceph:
    serviceID: odf
    placement:
      countPerHost: 1
    ingresses:
      - name: dc1
        address: 192.168.141.80
        prefixLength: 24
        virtualInterfaceNetworks:
          - 192.168.141.0/24
        placement:
          sites:
            - dc1
      - name: dc2
        address: 192.168.142.80
        prefixLength: 24
        virtualInterfaceNetworks:
          - 192.168.142.0/24
        placement:
          sites:
            - dc2
