apiVersion: bootwright.io/v1alpha1
kind: StorageObjectGateway
metadata:
  name: odf-rgw
spec:
  storageClusterRef:
    name: ceph-storage

  publicEndpointRef:
    name: rgw-public

  ceph:
    serviceID: odf
    placement:
      hosts:
        - ceph-dc1-0
        - ceph-dc1-1
        - ceph-dc1-2
        - ceph-dc2-0
        - ceph-dc2-1
        - ceph-dc2-2
      countPerHost: 1
    ingresses:
      - name: dc1
        endpointRef:
          name: rgw-dc1
        placement:
          hosts:
            - ceph-dc1-0
            - ceph-dc1-1
            - ceph-dc1-2
      - name: dc2
        endpointRef:
          name: rgw-dc2
        placement:
          hosts:
            - ceph-dc2-0
            - ceph-dc2-1
            - ceph-dc2-2
