apiVersion: bootwright.io/v1alpha1
kind: StorageExport
metadata:
  name: odf-external-ceph
spec:
  storageClusterRef:
    name: ceph-storage

  dataFoundation:
    rbdPoolRef:
      name: odf-rbd
    cephFSRef:
      name: odf-cephfs
    objectGatewayRef:
      name: odf-rgw
